### ISSUE TITLE
Supporto per modello di throttling interoperabile

### ISSUE THREAD

**Issue by ioggstream** [link-it/GovWay#1]
## Domanda

GovWay supporta già il modello di throttling interoperabile descritto [questo post](https://forum.italia.it/t/header-standardizzati-per-un-ecosistema-api-affidabile/3166)?

[Qui trovate una patch per kong](https://github.com/Kong/kong/pull/3451) che potreste riadattare nel caso.

**Comment by andreapoli** [comment]
Ciao @ioggstream, 
  ti confermo che GovWay supporta il modello descritto. Come avrai letto nella [documentazione](https://github.com/link-it/GovWay/blob/master/resources/doc/pdf/GovWay-ManualeUtente.pdf) disponibile e sul [sito](https://govway.org/) del progetto, nella modalità "API Gateway" abbiamo cercato di recepire tutte le indicazioni dei primi capitoli del nuovo modello ModI2018.

**Comment by ioggstream** [comment]
Ciao @andreapoli, ottimo. Ho trovato i riferimenti agli header nel codice (la doc non riportava i nomi).

Se avete feedback sulle Linee Guida o sui post di interoperabilità, sono benvenuti.
