### ISSUE TITLE
Errore GOVWAY_ORG_516

### ISSUE THREAD

**Issue by marcomarsala** [link-it/GovWay#12]
Inviando una fattura al sistema di test Sdi tramite GovWay ricevo il seguente errore:

```
<?xml version="1.0" encoding="UTF-8"?>
<ns2:fault xmlns:ns2="http://govway.org/integration/fault">
   <ns2:domain module="InoltroBuste" role="outboundProxy">
      <ns2:id>domain/sdi/Nineproof</ns2:id>
      <ns2:organization type="sdi">Nineproof</ns2:organization>
   </ns2:domain>
   <ns2:timestamp>2018-12-12T11:17:37.852+01:00</ns2:timestamp>
   <ns2:service>
      <ns2:sender>
         <ns2:id type="sdi">Nineproof</ns2:id>
         <ns2:domain-id>domain/sdi/Nineproof</ns2:domain-id>
      </ns2:sender>
      <ns2:provider>
         <ns2:id type="sdi">CentroServiziFatturaPA</ns2:id>
         <ns2:domain-id>domain/sdi/CentroServiziFatturaPA</ns2:domain-id>
      </ns2:provider>
      <ns2:service type="sdi" version="1">SdIRiceviFile</ns2:service>
      <ns2:action>RiceviFile</ns2:action>
      <ns2:application>SdIRiceviFile</ns2:application>
   </ns2:service>
   <ns2:exception type="integration">
      <ns2:code type="516">GOVWAY_ORG_516</ns2:code>
      <ns2:description>Servizio erogato dal Soggetto sdi-CentroServiziFatturaPA non disponibile</ns2:description>
   </ns2:exception>
</ns2:fault>
```

sul quale non riesco a trovare informazioni nella documentazione. Cos'è?

**Comment by andreapoli** [comment]
Nel caso in cui il Gateway rilevi errori durante il trattamento del messaggio (autorizzazione, validazione, consegna finale ...) la versione 3.0.0 genera un errore in un formato proprietario.

Nella nuova versione 3.0.1 (#6) è stato scelto di sostituire il formato proprietario con quello descritto nel RFC 7807 per essere in linea con il modello di interoperabilità:
- https://docs.italia.it/italia/piano-triennale-ict/lg-modellointeroperabilita-docs/it/stabile/doc/doc_02_cap_04.html
- https://forum.italia.it/t/messaggi-derrore-in-json-lo-standard-rfc7807/3115

Ti chiederei quindi di aggiornarti alla nuova versione 3.0.1 che verrà rilasciata stabile entro la settimana.

Puoi trovare documentazione a riguardo nel [manuale utente aggiornato](https://github.com/link-it/GovWay/blob/master/resources/doc/pdf/GovWay-ManualeUtente.pdf), nella sezione '2.2.3 Errori Generati dal Gateway' e '8.6 Errori Generati dal Gateway'.

**Comment by marcomarsala** [comment]
Sostanzialmente non ho modo di capire cosa non va fino al rilascio della prossima versione?

**Comment by andreapoli** [comment]
Sono due cose differenti il formato dell'errore ritornato al client e l'analisi dell'errore.

Mi avevi chiesto spiegazioni su cosa fosse il fault ricevuto, poichè non ne avevi trovato documentazione e ti ho risposto che si tratta di un formato proprietario deprecato a favore del RFC 7807 utilizzato nella nuova versione.

Per comprendere invece cosa non va non serve attendere la nuova versione :-)
Basta utilizzare la console 'govwayMonitor', esaminando i diagnostici della transazione in errore.

Il fault ritornato al client riporta solamente una descrizione generica che indica l'indisponibilità del servizio dello SDI.

**Comment by marcomarsala** [comment]
Fantastico. Sono riuscito a usare il monitor e ho trovato la descrizione dettagliata del problema.

**Comment by marcomarsala** [comment]
Che però non so risolvere. L’errore che vedo è “Keystore [/var/govway/fatturapa.p12] not found“, tuttavia nella configurazione del connettore della fruizione SDIRiceviFile ho specificato un altro percorso, precisamente /var/govway/fatturapa.jks

Non capisco dove prenda questo percorso, non lo trovo in nessuna schermata di GovWay.

**Comment by andreapoli** [comment]
Le configurazioni vengono mantenute da GovWay in una cache per 2 ore dopo il primo accesso.
Se hai modificato la configurazione puoi forzare un reset della cache tramite 'govwayConsole' accedendo alla sezione 'Strumenti' - 'Runtime' e selezionare la voce 'ResetAllCaches'.

**Comment by marcomarsala** [comment]
Funziona! Prima fattura inviata. Grazie
