### ISSUE TITLE
Connettore CentroServiziFatturaPA

### ISSUE THREAD

**Issue by marcomarsala** [link-it/GovWay#13]
Di default in **Soggetti > CentroServiziFatturaPA** il connettore risulta disabilitato. E' corretto? A cosa serve?

Abilitandolo (connettore file), poi non si può più disabilitare in quanto ritorna il messaggio di errore:

`Il connettore deve essere specificato poichè alcuni servizi del soggetto non hanno un connettore definito.`

![image](https://user-images.githubusercontent.com/5349718/49866654-a4a0df80-fe08-11e8-83b0-f86bc558d6ea.png)

**Comment by andreapoli** [comment]
La possibilità di modificare un connettore nel soggetto è un bug.
Il connettore deve essere configurato nell'erogazione o nella fruizione.
Il problema è stato risolto nella nuova versione 2.3.1.

**Comment by marcomarsala** [comment]
Perfetto. Posso lasciare attivato il connettore che ho configurato per il soggetto o crea problemi? Se rifaccio l’importazione del govlet va a posto?

**Comment by andreapoli** [comment]
Non dovrebbe creare problemi poichè viene comunque utilizzato il connettore specificato nella fruizione.

Verifica magari che il connettore associato alla fruizione di 'SdiRiceviFile' (erogato da CentroServiziFatturaPA) sia quello atteso.

**Comment by marcomarsala** [comment]
Si, nel campo Connettore è riportato https://testservizi.fatturapa.it/ricevi_file e entrando dentro ci sono i dati del mio .jks che avevo inserito, quindi direi che è ok. Grazie.
