### ISSUE TITLE
govway docker: caricamento zip di configurazione ad avvio container

### ISSUE THREAD

**Issue by Ettore-Morasso** [link-it/govway#135]
Salve,
scrivo per chiedere un chiarimento sulla possibilità o meno di effettuare alcune configurazioni automaticamente all'avvio del container.
Situazione:
- dispongo di un file zip contente il dump completo della configurazione di un'istanza di govway
- preparo uno yaml per eseguire l'applicativo su ambiente docker
- il database per questo nuovo container è pulito e verrà popolato all'avvio del container govway
- E' possibile far caricare all'avvio del container govway la configurazione precedentemente salvata nello zip, piuttosto che importarla da interfaccia web? Se si, come?

Grazie

**Comment by marklar79** [comment]
Buongiorno

Gli  archivi di configurazione sono importabili in due modi :
1. tramite l'interfaccia web
2. tramite un tool a linea di comando

Al momento il tool a linea di comando non è inserito nell'immagine docker e non esiste  una immagine a se stante.
Se vi può interessare i sorgenti sono disponibili su github: 

https://github.com/link-it/govway/tree/master/tools/command_line_interfaces/config_loader

Saluti

**Comment by Ettore-Morasso** [comment]
D'accordo, grazie
