### ISSUE TITLE
Supporto servizio Monitoraggio_v1.0

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#14]
Buongiorno,

GovWay supporta il servizio `Monitoraggio_v1.0`?

Si trova sul sito FatturaPA al percorso **Strumenti > Monitorare la FatturaPA > Report**: https://sdi.fatturapa.gov.it/SdI2FatturaPAWeb/sicurezza/AccediAlServizioAction.do?pagina=report

WSDL: https://sdi.fatturapa.gov.it/SdI2FatturaPAWeb/sicurezza/DownloadMonitoraggioFileAction.do?tipoFile=wsdl

**Comment by andreapoli** [comment]
GovWay può essere utilizzato come API Gateway per qualsiasi servizio SOAP e REST.

Nel caso specifico si tratta di un normale servizio SOAP che puoi registrare utilizzando il profilo 'API Gateway' seguendo le indicazioni presenti nella sezione '2.3 Registrazione della fruizione'  del [manuale utente](https://github.com/link-it/govway/blob/master/resources/doc/pdf/GovWay-ManualeUtente.pdf).

In futuro estenderemo le govlet di fatturazione al fine di prevedere la configurazione automatica di tale servizio.
