### ISSUE TITLE
errore nella creazione del token di AUDIT-01/02 

### ISSUE THREAD

**Issue by AlessandroCimarelli** [link-it/govway#141]
Ciao, 
stiamo testando il GovWay con le funzionalità AUDIT-01/02 e INTEGRITY-01/02 ma non riusciamo a far generare i token richiesti dalle linee guida AGID.

AUTH-01/02 funzionano correttamente e ci viene staccato il token PDND.

Mentre se abilitiamo AUDIT-01/02 sul API e lo configuriamo su un servizio in FRUIZIONE o EROGAZIONE abbiamo il seguente errore 

"Riscontrato errore durante la gestione del messaggio [imbustatore.after-sec.imbustamento]: Il profilo di sicurezza richiesto 'null' richiede l'identificazione di un applicativo"

allego gli screenshoot delle configurazioni

![Schermata del 2023-11-15 08-59-56](https://github.com/link-it/govway/assets/46533148/ce29ce70-d667-4e6e-a73f-7608677125d9)
![Schermata del 2023-11-15 09-00-45](https://github.com/link-it/govway/assets/46533148/dd793bbe-2196-4c55-97d8-78a9b49db673)
![Schermata del 2023-11-15 09-02-39](https://github.com/link-it/govway/assets/46533148/b0e11dac-8d6a-4d88-93d5-f1e97b516c35)

potete aiutarci a capire dove sia il problema?

Grazie
Alessandro Cimarelli

**Comment by AlessandroCimarelli** [comment]
Ho dimenticato di scrivere la versione che stiamo utilizzando:
GovWay 3.3.13

**Comment by andreapoli** [comment]
Buongiorno @AlessandroCimarelli ,

   l'errore è dovuto al fatto che non viene identificato un applicativo fruitore. 
   
Per firmare il token di audit (o di integrity) viene utilizzato il keystore definito nell'applicativo come indicato nella configurazione che hai riportato: "Sicurezza Messaggio - Keystore: definito nell'applicativo".
Questa configurazione, descritta nella [documentazione](https://govway.org/documentazione/console/profiloModIPA/messaggio/idar01/x509/idar01_fruizione.html), richiede:
- un'autenticazione configurata nel controllo degli accessi della fruizione;
- la definizione di un applicativo che possiede credenziali di accesso compatibili con l'autenticazione e i dati necessari a firmare il token di audit (keystore)

In alternativa puoi definire il [keystore nella fruizione](https://govway.org/documentazione/console/profiloModIPA/messaggio/avanzata/fruizione_keystore.html#modipa-sicurezza-avanzate-fruizione-keystore).
   
La diagnostica che hai riportato non riportava le informazioni corrette per comprendere la problematica e infatti è stato realizzato un fix nel commit b4dc6d87588d00bc06f8f07832f417a01a2989ff

**Comment by AlessandroCimarelli** [comment]
Ciao Andrea,
abbiamo risolto il problema e ora non abbiamo più errore, infatti nei log troviamo

2023-11-15 11:04:43.879	infoIntegration	ModI	Creazione security token ModI 'AUDIT' della richiesta in corso ...
2023-11-15 11:04:44.618	infoIntegration	ModI	Creazione security token ModI 'AUDIT' della richiesta effettuata con successo

Però al servizio di arrivo non vediamo l'header AgiD-JWT-TrackingEvidence nella richiesta

C'è qualche altra operazione da fare?

Alessandro

**Comment by andreapoli** [comment]
Ciao Alessandro, 
    per servizio di arrivo intendi il backend agganciato ad una erogazione ?
    
Se così fosse i Token ModI, dopo essere stati validati da GovWay, vengono eliminati dai messaggi in modo da rendere trasparente agli applicativi la gestione della sicurezza effettuata sul Gateway.

Al backend vengono inviate informazioni puntuali estratte dai token ModI ed inserite in header HTTP dedicati.
Puoi vedere sia gli header che i contenuti scambiati abilitando la funzione di [registrazione messaggi](https://govway.org/documentazione/console/profiloApiGateway/registrazioneMessaggi/index.html).

Se invece hai necessità di veicolare verso il backend il token Agid-JWT-TrackingEvidence ricevuto puoi disabilitare lo sbustamento ModI seguendo le indicazioni della [documentazione](https://govway.org/documentazione/console/profiloModIPA/messaggio/avanzata/sbustamento.html).

**Comment by AlessandroCimarelli** [comment]
Scusa Andrea, 

ero io che nel mio be di test, che simula un ente esterno toglievo i security header.

Quindi funziona correttamente :-D

grazie
Alessandro
