### ISSUE TITLE
Deploy govwayConsole.war su Wildfly (26.1.3) - Errore: "Non esiste un protocollo associato al tipo di soggetto"

### ISSUE THREAD

**Issue by ddc111** [link-it/govway#142]
Ciao,
viene riscontrato un errore quando viene deployato il pacchetto govwayConsole.war su WildFly 26.1.3.Final.
Gli altri pacchetti vengono deployati con successo.

Errore: 

2023-11-17 13:07:38,119 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 109) MSC000001: Failed to start service jboss.deployment.unit."govwayConsole.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.unit."govwayConsole.war".undertow-deployment: java.lang.R
untimeException: java.lang.RuntimeException: Errore durante l'inizializzazione del loader dei plugins: [ControlStationCore::getConfigurazioneGenerale] Exception:[ControlStationCore::getProtocolloAssociatoTipoSoggetto] **Exception:Non esiste un protocollo associato al tipo di soggetto [as4]**
        at org.wildfly.extension.undertow@26.1.3.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:90)

**Comment by andreapoli** [comment]
Buonasera @ddc111,
  dall'errore riportato sembrerebbe che la base dati sia inconsistente rispetto agli archivi dispiegati sull'application server. 
  
Questo potrebbe verificarsi se l'installer è stato stato eseguito più volte fornendo dati differenti in input.
Ipotizzo che nella prima esecuzione sia stato selezionato il profilo di interoperabilità 'eDelivery' e siano stati utilizzati gli script sql per creare il database.
In una seconda esecuzione non sia invece stato selezionato il profilo di interoperabilità 'eDelivery' e sia stati utilizzati gli archivi war/ear per il dispiegamento sull'application server.
Di fatto quindi nella base dati è presente una configurazione non utilizzabile dal software dispiegato.

**Comment by ddc111** [comment]
Buonasera,
confermo, il problema nasce dall'utilizzo di uno stesso DB per una seconda installazione senza profilo "eDelivery", dove la prima installazione invece prevedeva il profilo "eDelivery".
