### ISSUE TITLE
Errore 503 su accesso PDND Servizio applicativo anonimo

### ISSUE THREAD

**Issue by mfortini** [link-it/govway#143]
Ho configurato un'istanza locale (docker) di GovWay secondo le istruzioni qui https://govway.readthedocs.io/it/latest/scenari/modipa/idauth_pdnd/fruizione_modipa_rest/configurazione.html e mi restituisce un errore 503, non sono riuscito a capire quale configurazione manchi. 

![image](https://github.com/link-it/govway/assets/1104926/53a56765-7309-4f45-9f6a-52b8ca398239)

**Comment by andreapoli** [comment]
Buonasera @mfortini,
   la problematica segnalata sembra essere simile a quanto riscontrato nell'issue #141 .

Tanto premesso la token policy di negoziazione che hai utilizzato nel connettore (api-pdnd) viene fornita built-in dal prodotto ed è specifica per ottenere un token necessario ad utilizzare le api di PDND di interoperabilità utilizzando un client di tipo 'api interop' come descritto nella documentazione [API PDND](https://govway.readthedocs.io/it/latest/console/profiloModIPA/messaggio/passiPreliminari/apiPDND.html). Dentro la configurazione infatti per default non troverai abilitato il flag 'PDND' poichè la policy non deve gestire il 'purposeId' in quanto non richiesto dalla PDND per ottenere un token spendibile sulle sue api di interoperabilità.
    
Se l'obiettivo è invece quello di negoziare un voucher tramite un client generico di tipo 'e-service', come descritto nelle [istruzioni riferite](https://govway.readthedocs.io/it/latest/scenari/modipa/idauth_pdnd/fruizione_modipa_rest/configurazione.html) o anche nella seguente [documentazione](https://govway.readthedocs.io/it/latest/console/profiloModIPA/messaggio/idar01/pdnd/pdnd_fruizione.html), dovresti definire una token policy di negoziazione con il flag PDND abilitato e associarlo al connettore della tua fruizione.

La token policy può supportare tre scenari differenti, come troverai descritto nella [documentazione](https://govway.readthedocs.io/it/latest/console/profiloModIPA/messaggio/idar01/pdnd/pdnd_fruizione.html):
- definire i dati relativi ai keystore delle chiavi, al kid e al clientId nell'applicativo fruitore (modalità: "Definito nell’applicativo ModI");  in questo caso devi anche registrare un applicativo che conterrà tutti i dati, associargli delle credenziali di accesso a GovWay e abilitare un tipo di autenticazione nel controllo degli accessi della fruizione compatibile con le credenziali di accesso definite nell'applicativo;
- definire i dati relativi ai keystore delle chiavi, al kid e al clientId direttamente nella fruizione (modalità: "Definito nella fruizione ModI");
- cablare i dati direttamente nella token policy.

Inoltre anche la gestione del purposeId può essere realizzata tramite differenti scenari. Nella [documentazione](https://govway.readthedocs.io/it/latest/console/profiloModIPA/messaggio/idar01/pdnd/pdnd_fruizione.html) troverai descritti tutti i possibili scenari supportati a riguardo.

**Comment by mfortini** [comment]
La finalità è quella di accedere a un eservice.

Inserisco qui la configurazione se può essere utile

![image](https://github.com/link-it/govway/assets/1104926/6971d96f-2298-40ac-8c27-c8f30184da86)

![image](https://github.com/link-it/govway/assets/1104926/b9fc9d69-688c-4769-86af-2cfdec0c996c)

![image](https://github.com/link-it/govway/assets/1104926/307aa521-1d43-493e-97e0-bcd7de7a822c)

**Comment by andreapoli** [comment]
Tra gli screenshot forniti manca la configurazione del controllo degli accessi della fruizione.

Verifica di aver impostato nel controllo degli accessi della fruizione un'autenticazione di tipo http-basic. Molto probabilmente l'autenticazione è disabilitata mentre il tipo di token policy configurato richiede l'autenticazione di un applicativo.

**Comment by mfortini** [comment]
Grazie, la correzione di attivare l'autenticazione mi ha permesso di superare questo problema
