### ISSUE TITLE
url JWK Set

### ISSUE THREAD

**Issue by AlessandroCimarelli** [link-it/govway#145]
**Necessità:**
Ci servirebbe che il JWK Set, oltre ad essere associato ad un file, sia una url, visto che i jwks sono spesso esposti via web

**Soluzione:**
inserimento della url jwks,  la response inserita in una cache con validità che sia possibile definire e pulire.

**Comment by andreapoli** [comment]
Buonasera @AlessandroCimarelli ,
   già adesso è possibile indicare una url per effettuare il download dei jwks. Allo stato attuale non è però possibile definire i criteri di trust per la connessione https (hostname verify, truststore ...). Il trust deve essere configurato a livello di proprietà java (es: javax.net.ssl.trustStore) dell'application server. 
    
![Configurazione](https://github.com/link-it/govway/assets/16049098/ea02de2e-73b2-4f11-86b4-953efb4d33b3)

I keystore e le chiavi, una volta acceduti vengono salvati in una cache dedicata dove è possibile impostare il tempo di vita come descritto nella documentazione [cache dedicata ](https://govway.readthedocs.io/it/latest/installazione/finalizzazione/cache.html#govwaycaches).

![Keystore](https://github.com/link-it/govway/assets/16049098/f9e05f97-ca3b-4d98-9d77-c48e6cdd0a3c)

**Comment by AlessandroCimarelli** [comment]
Perfetto, quindi devo solo inserire nel truststore di Java il certificato o la CA del server in https dove viene esposto il jwks.

Grazie
Alessandro
