### ISSUE TITLE
Riscontrato errore durante la negoziazione del token con PDND

### ISSUE THREAD

**Issue by mfortini** [link-it/govway#147]
Non capisco se questo errore sia relativo alla configurazione PDND o a quella di interazione con l'eService

![image](https://github.com/link-it/govway/assets/1104926/0614aa7b-26d4-4658-8110-2196b679cd47)

**Comment by andreapoli** [comment]
Buongiorno @mfortini,
  
   l'errore json riportato nel log con codice di trasporto http 400 viene generato dalla PDND al momento dello stacco del voucher. 
   
Prova ad esaminare il tab 'Informazioni Mittente' dove dovrebbero esserci maggiori informazioni riguardanti la negoziazione in corso.

**Comment by andreapoli** [comment]
Perfetto dovresti avere tutte le informazioni necessarie per chiedere supporto a PDND sulla mancata negoziazione del token.
