### ISSUE TITLE
UndefinedOperation per path esistente

### ISSUE THREAD

**Issue by mfortini** [link-it/govway#148]
Sto cercando di accedere a un path definito nell'API, ma ricevo un 404 con "undefined operation"

![image](https://github.com/link-it/govway/assets/1104926/3b4c133a-5e4b-4e4c-98f9-4300e9bf8325)

![image](https://github.com/link-it/govway/assets/1104926/81e05d09-7ae5-457e-a0de-b4940fdba9c7)

**Comment by andreapoli** [comment]
Buongiorno @mfortini ,

 per poterti aiutare dovresti effettuare lo screenshot anche del tab 'Informazioni Mittente', nel dettaglio della transazione, dove si può comprendere la url che stai utilizzando per invocare il servizio.

**Comment by andreapoli** [comment]
Dalle risorse che hai indicato nella [configurazione](https://github.com/link-it/govway/issues/148#issue-2003849570)  la risorsa status è definita con il path '/status'.

Il mancato riconoscimento dell'operazione è dovuto al fatto che dopo la base url '.../govway/rest/out/Ente/MUR/MUR_Titoli/v1' nella tua chiamata stai indirizzando una risorsa con path '/it/status' che effettivamente non esiste nell'API.

**Comment by mfortini** [comment]
Corretto. Grazie mille
