### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by AlessandroCimarelli** [link-it/govway#149]
Ciao,
dove posso trovare la documentazione per creare un plugin di NegoziazioneTokenParser ?

Grazie
Alessandro

**Comment by andreapoli** [comment]
Per registrare un plugin devi collegarti alla console di gestione in [modalità avanzata](https://govway.org/documentazione/console/avanzate/modalita_avanzata.html).

Dopodichè devi accedere alla sezione "Configurazione Generale - Registro Classi":

![Plugins](https://github.com/link-it/govway/assets/16049098/3a8f2fc0-af34-4402-9fc4-a38515b83d7d)

Registrare il plugin indicando il classname della classe che implementa l'interfaccia [org.openspcoop2.pdd.core.token.parser.INegoziazioneTokenParser](https://github.com/link-it/govway/blob/master/core/src/org/openspcoop2/pdd/core/token/parser/INegoziazioneTokenParser.java)

![Plugin](https://github.com/link-it/govway/assets/16049098/8e907984-057d-45fe-be0d-7bfd6761ada5)

Una volta registrato il plugin, potrà essere selezionato nella configurazione della policy:

![Parser](https://github.com/link-it/govway/assets/16049098/d1d1fe52-3f42-45d5-84f1-fbcccbb07a3d)

La classe java dovrà essere inserita all'interno delle lib dell'archivio 'govway.ear/lib'.
In alternativa puoi registrare un archivio jar accendendo alla sezione "Configurazione Generale - Registro Classi"

**Comment by AlessandroCimarelli** [comment]
Ciao,
avevo visto la possbilità di utilizzare i plugin, che è un parte molto interessante, da utilizzare in caso di tipologie di negozazione interna alla propria infrastruttura diversa dagli standard.

Quello che chiedevo è se c'è una classe di esempio da cui partire e poi modificare per l'esigenza non standard.

Ho visto nella documentazione la parte di validazione dove si utilizza eclipse e SpotBugs Eclipse Plugin.

C'è una documentazione, tipo la validazione, per i plugin,un esempio da cui partire,  così da creare corremente una classe con tutte le specifiche per funzionare?

Alessandro

**Comment by andreapoli** [comment]
Buongiorno @AlessandroCimarelli,

   per la maggior parte dei plugin esistono già delle implementazioni built-in che normalmente si utilizza tramite le normali configurazioni attivate sulla console di gestione. Puoi quindi basarti sulle implementazioni built-in dell'interfaccia di un plugin per avere un esempio da cui partire.
   
 Nel tuo caso specifico la classe [BasicNegoziazioneTokenParser.java](https://github.com/link-it/govway/blob/master/core/src/org/openspcoop2/pdd/core/token/parser/BasicNegoziazioneTokenParser.java) è l'implementazione dell'interfaccia [INegoziazioneTokenParser.java](https://github.com/link-it/govway/blob/master/core/src/org/openspcoop2/pdd/core/token/parser/INegoziazioneTokenParser.java).

**Comment by AlessandroCimarelli** [comment]
ottimo, mi metto subito a lavorarci.

grazie mille
Alessandro
