### ISSUE TITLE
Documentazione: Figura 87 - Dati di configurazione di un connettore file

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#15]
Nella documentazione, la Figura 87 - Dati di configurazione di un connettore file riporta i campi File e File Headers compilati con il path di un file.

Più sopra invece si dice:

> File: indirizzo su file-system (path) dove verrà serializzato il messaggio di richiesta. È possibile fornire delle macro per
> creare dei path dinamici (per ulteriori dettagli vedi sezione ’Informazioni Dinamiche’).

Mi aspetterei di dover inserire una directory in questi campi (può essere la stessa per entrambi?), nella quale il connettore scriverà i file ricevuti, che hanno già un nome univoco come da [Allegato B-1 del documento Specifiche tecniche relative al Sistema di Interscambio](https://www.fatturapa.gov.it/export/fatturazione/it/normativa/f-3.htm), è corretto?

Segnalo che l'impaginazione sembra rotta su quella pagina.

**Comment by andreapoli** [comment]
# Premessa
Il Connettore File è una funzionalità generica di GovWay indipendente dal profilo 'Fatturazione Elettronica', ed utilizzabile anche negli altri profili supportati (API Gateway, SPCoop, eDelivery). Per questo motivo il path che inserisci deve identificare un file e non una directory, visto che non in tutti i profili è disponibile una informazione che identifica univocamente il nome di un file.
Per poter serializzare la richiesta in un file sempre differente è possibile utilizzare le macro descritte in 'Informazioni Dinamiche'. 
Un esempio di path dinamico è '/tmp/{transaction:id}.xml' per File e '/tmp/{transaction:id}.properties' per File Headers.

# Path dinamico per la fatturazione
Il nome del file di una fattura viene riportato come header 'GovWay-SDI-NomeFile'.
Questa informazione potrebbe essere utilizzata per realizzare la dinamicità da te richiesta in una formula simile alla seguente: '/tmp/{header:GovWay-SDI-NomeFile}.xml'.
Ho aperto un issue (#17) in modo da includere la funzionalità in una prossima versione.

**Comment by marcomarsala** [comment]
Al momento non è possibile farlo con il nome del file? Ora sto usando `{transaction:id}`

**Comment by andreapoli** [comment]
Al momento no. Ho aperto l'issue #17 in modo da includere la funzionalità in una prossima versione.
