### ISSUE TITLE
Erogare su PDND una api protetta con api-key nel dominio interno

### ISSUE THREAD

**Issue by ilkosta** [link-it/govway#159]
## scenario da realizzare

Configurare una erogazione tramite PDND.
L'API fornita dall'applicativo interno al dominio richiede accesso con api-key.

## risultato attuale

* Nella configurazione del connettore non risulta possibile specificare il metodo api-key
* Nella configurazione del connettore non è possibile specificare `Utilizza applicativo server`.

## risultato atteso

* Poter specificare l'api-key da usare per invocare l'applicativo interno al dominio.
* Poter specificare l'applicativo server del dominio interno da invocare.

**Comment by andreapoli** [comment]
Buonasera @ilkosta.

Ci è chiara la richiesta di aggiungere la possibilità di definire una api-key direttamente nel connettore e verrà presa in considerazione per le prossime versioni. Come workaround in attesa che venga realizzata puoi utilizzare una [trasformazione](https://govway.org/documentazione/console/profiloApiGateway/trasformazioni/trasformazioneRichiesta.html) aggiungendo l'header desiderato.

La seconda richiesta invece non è chiara poiché la possibilità di indicare un [applicativo server](https://govway.org/documentazione/console/profiloApiGateway/connettore/applicativoServer.html) nel connettore è già supportato. Potresti spiegare più dettagliatamente l'esigenza che ritieni non soddisfatta?

**Comment by andreapoli** [comment]
Aggiunta possibilità di configurare nel connettore il metodo di autenticazione api-key, all'interno dell'intervento realizzato nel commit 255c560
