### ISSUE TITLE
Connettore Ridefinito in un gruppo non è visualizzabile in modalità 'standard' della Console

### ISSUE THREAD

**Issue by andreapoli** [link-it/govway#16]
# Contesto 
La suddivisione delle azioni/risorse di una erogazione/fruizione in gruppi permette di associare configurazioni differenti (autorizzazione, validazione, rateLimiting ...) ad ogni gruppo.
Se la govwayConsole viene utilizzata in "modalità avanzata" è possibile ridefinire anche il connettore per il singolo gruppo. 
La ridefinizione di un connettore su un gruppo disabilita la possibilità di configurazione globalmente il connettore sull'intera erogazione/fruizione. Per modificarlo si deve agire sul singolo gruppo poichè non esiste più una configurazione complessiva valida per tutte le azioni/risorse dell'api.

# Esempio di Utilizzo: Fatturazione Passiva
La ridefinizione di un connettore sul gruppo viene ad esempio utilizzata dal govlet di Fatturazione Passiva che suddivide le due azioni (RiceviFatture e NotificaDecorrenzaTermini) previste per il servizio RicezioneFatture in due gruppi in modo da rendere possibile una gestione differente.

# Problema emerso 
Se tramite la "modalità avanzata" della govwayConsole è stato ridefinito un connettore per un gruppo,
tornando alla "modalità standard" la gestione dei connettori sui gruppi non è più utilizzabile, e nello stesso tempo non è più possibile configurare il connettore globalmente sull'erogazione/fruizione.

# Soluzione
Nel caso uno dei gruppi possieda una ridefinizione del connettore, la gestione dei connettori nei gruppi deve essere effettuabile anche con un utilizzo in "modalità standard" della govwayConsole.

**Comment by marcomarsala** [comment]
Sono già in modalità avanzata. Trovato, grazie.

Perché però vicino a Fatture mi mostra "visualizza" e vicino a "Notifiche di decorrenza termini" mi mostra "ridefinito" o "standard" in base a cosa seleziono entrando dentro?
![image](https://user-images.githubusercontent.com/5349718/49952068-a26b7d80-fefb-11e8-93ee-1390177adc1b.png)

**Comment by andreapoli** [comment]
La suddivisione in gruppi prevede l'esistenza sempre di un gruppo predefinito che raccoglie tutte le azioni/risorse di una API non collezionate in gruppi creati ad hoc (inizialmente tutte).
Il connettore iniziale specificato al momento della creazione di una erogazione/fruizione corrisponde al gruppo predefinito e quindi per modificarlo devi usare il link 'visualizza'.
Negli altri gruppi creati ad hoc sarà possibile invece indicare per il connettore:
- 'default': viene utilizzato lo stesso connettore impostato per il gruppo predefinito
- 'ridefinito': in questo caso viene completamente ridefinito un nuovo connettore.

Quanto premesso la govlet di fatturazione passiva rinomina il gruppo predefinito in 'Fatture (Metadati)'.
