### ISSUE TITLE
Integrazione con gestionali per aziende private

### ISSUE THREAD

**Issue by sergiocorato** [link-it/govway#164]
Buongiorno,
ho visto questo progetto ed è molto interessante.
Il mio dubbio è se sia possibile utilizzarlo, in particolare il `Profilo “Fatturazione Elettronica”`, per l'invio/ricezione di fatture elettroniche da un gestionale, con un apposito connettore, per aziende private.
Grazie.

**Comment by andreapoli** [comment]
Buongiorno @sergiocorato, 
   trovi tutte le funzionalità supportate nella documentazione del profilo [Fatturazione Elettronica](https://govway.org/documentazione/console/profiloFatturaPA/index.html) tra cui dovrebbe rientrare anche la tua esigenza.
   
Puoi riscontrare tra le issue (es. [9](https://github.com/link-it/govway/issues/9), [36](https://github.com/link-it/govway/issues/36)) e anche sul forum (es. [webservice-trasmissionefatture di forum.italia](https://forum.italia.it/t/webservice-trasmissionefatture/3682/53)) utilizzi simili da parte di un utente.

**Comment by sergiocorato** [comment]
Buondì @andreapoli,
stupendo, grazie mille!
