### ISSUE TITLE
Conferma Agid-JWT-TrackingEvidence verificato solo su AUDIT_REST_01

### ISSUE THREAD

**Issue by nicolabeghin** [link-it/govway#167]
Una precisazione/conferma/dubbio: è corretto affermare che di default allo stato attuale il token `Agid-JWT-TrackingEvidence` è verificato solo con `AUDIT_REST_01` e `AUDIT_REST_02`? Da quanto capisco con `INTEGRITY_REST_01` viene verificato `Agid-JWT-Signature` e non il `Agid-JWT-TrackingEvidence` [richiesto da PDND](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher#il-flusso-in-breve).

grazie
nicola

**Comment by andreapoli** [comment]
Buongiorno @nicolabeghin.

Si tratta di 2 token di sicurezza da utilizzare per scopi differenti che non si escludono a vicenda e possono essere utilizzati/richiesti insieme.

In una API puoi abilitare entrambi i pattern come descritto nelle sezioni [INTEGRITY_REST_02](https://govway.org/documentazione/console/profiloModIPA/messaggio/idar03/pdnd/index.html) e [AUDIT_REST_01 / AUDIT_REST_02](https://govway.org/documentazione/console/profiloModIPA/messaggio/audit/index.html)

![Screenshot from 2024-08-03 11-03-59](https://github.com/user-attachments/assets/a83b0136-87c9-4ef3-aebc-4c430345197c)


Il token 'Agid-JWT-TrackingEvidence' verrà prodotto o atteso/validato solo se attivato il pattern [AUDIT_REST_01 / AUDIT_REST_02](https://govway.org/documentazione/console/profiloModIPA/messaggio/audit/index.html) corrispondente.

**Comment by nicolabeghin** [comment]
Grazie per la conferma, chiudo!
