### ISSUE TITLE
AUDIT_REST_01 richiedente in Agid-JWT-TrackingEvidence claims non obbligatori da RFC 7519 e 7515: aud,jti,iat,exp 

### ISSUE THREAD

**Issue by nicolabeghin** [link-it/govway#168]
**Descrizione del Bug**
Inviando token `Agid-JWT-TrackingEvidence` con profilo audit [`AUDIT_REST_01`](https://govway.org/documentazione/console/profiloModIPA/messaggio/audit/audit01/index.html) attivato govway richiede obbligatoriamente i seguenti claim che non sono obbligatori da [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6) e [RFC 7515](https://datatracker.ietf.org/doc/html/rfc7515)
* `aud`: audience
* `jti`: UUID4
* `iat`: issued 
* `exp`: expiration

Riferimento codice: https://github.com/link-it/govway/blob/07ecc8cb5cdcc16ac77c54b25a4eb0db785759b7/protocolli/modipa/src/org/openspcoop2/protocol/modipa/validator/ModIValidazioneSintatticaRest.java#L953

Non chiaro se tali claim siano obbligatori o meno anche per PDND: issue https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/issues/212

**Come riprodurlo:**
Inviare token `Agid-JWT-TrackingEvidence` con profilo audit [`AUDIT_REST_01`](https://govway.org/documentazione/console/profiloModIPA/messaggio/audit/audit01/index.html) attivato senza uno dei seguenti claim: `aud,jti,iat,exp` - ad esempio `iat`

**Risultato atteso:**
Token accettato

**Screenshots:**
<img width="980" alt="image" src="https://github.com/user-attachments/assets/4f184520-4541-4bbf-b304-cba5e8db9128">

**Ambiente:**
 - OS: Docker (govway-docker)
 - Browser: [e.g. Chrome 75]
 - GovWay: 3.3.14
 - AS: Tomcat9
 - DBMS: Postgres

**Note aggiuntive:**
Effettuato un dummy check se fosse possibile effettuare un override tramite configurazione, ma non funziona

    org.openspcoop2.protocol.modipa.sicurezzaMessaggio.audit.pattern.optional.claims.iat.nome=iat
    org.openspcoop2.protocol.modipa.sicurezzaMessaggio.audit.pattern.optional.claims.iat.label=Issued
    org.openspcoop2.protocol.modipa.sicurezzaMessaggio.audit.pattern.optional.claims.iat.required=false
    org.openspcoop2.protocol.modipa.sicurezzaMessaggio.audit.pattern.optional.claims.iat.stringType=true
    org.openspcoop2.protocol.modipa.sicurezzaMessaggio.audit.pattern.optional.claims.iat.info=iat
    org.openspcoop2.protocol.modipa.sicurezzaMessaggio.audit.pattern.optional.claims.iat.rule=${header:GovWay-Audit-User},${query:govway_audit_user}
    org.openspcoop2.protocol.modipa.sicurezzaMessaggio.audit.pattern.optional.claims.iat.rule.info=Header http 'GovWay-Audit-User',Parametro della url 'govway_audit_user'
    org.openspcoop2.protocol.modipa.sicurezzaMessaggio.audit.pattern.optional.claims.iat.forwardBackend=
    org.openspcoop2.protocol.modipa.sicurezzaMessaggio.audit.pattern.optional.claims.iat.trace=false

**Comment by andreapoli** [comment]
Buongiorno @nicolabeghin.

I claim indicati sono definiti come obbligatori da Agid nelle "Linee Guida sull’interoperabilità tecnica delle Pubbliche Amministrazioni –Pattern di sicurezza" nel capitolo "6.1 [AUDIT_REST_01] Inoltro dati tracciati nel dominio del Fruitore REST"

Riporto alcuni frammenti della specifica:

![Screenshot from 2024-08-03 10-53-07](https://github.com/user-attachments/assets/b8be1dcc-76b0-4cf2-8623-2d6e16321225)

![Screenshot from 2024-08-03 10-54-31](https://github.com/user-attachments/assets/0c43299a-3300-4cb5-ab19-cc2083e1d47a)

**Comment by andreapoli** [comment]
> override tramite configurazione, ma non funziona

Non è possibile effettuare l'override dei suddetti campi poichè ritenuti obbligatori da Agid.

**Comment by nicolabeghin** [comment]
Grazie @andreapoli credo tu sia la persona più competente in materia di tutta Italia! Linkato anche nel ticket di PDND https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/issues/212 e chiudo.

**Comment by denismarini** [comment]
Buongiorno @nicolabeghin,

Un’osservazione riguardo al protocollo [AUDIT_REST_01]: l’inoltro dei dati tracciati nel dominio del Fruitore REST. Questo tipo di comunicazione viene utilizzata in casi molto specifici, quando la normativa impone all’erogatore di acquisire dati tracciati nel dominio del fruitore.

<img width="1031" alt="image" src="https://github.com/user-attachments/assets/094022bf-67f6-43b1-a2fc-2bc5d63f6435">

Pertanto, viene richiesta anche l’inclusione di informazioni aggiuntive nella pubblicazione dell’e-service da parte dell’erogatore. 

<img width="1035" alt="image" src="https://github.com/user-attachments/assets/a5e48cda-4ae2-477f-b11b-9be76e922d75">

**Comment by nicolabeghin** [comment]
> Pertanto, viene richiesta anche l’inclusione di informazioni aggiuntive nella pubblicazione dell’e-service da parte dell’erogatore.
Sicuramente, ma claim custom aggiuntivi rappresentano un di più rispetto a quelli obbligatori richiesti dal token in oggetto motivo per il quale @andreapoli ha risposto (a mio parere) in maniera inappuntabile. Lato nostro non richiederemo claim aggiuntivi neppure quelli aggiuntivi previsti da AUDIT_01 quindi documenteremo che sono richiesti solo quelli obbligatori da documentazione ufficiale.

**Comment by denismarini** [comment]
Il profilo di sicurezza da utilizzare nella 1.3.1 UNIAFAM è quello base per il protocollo REST, ossia [ID_AUTH_REST_01] Direct Trust con certificato X.509 REST e non sono richieste informazioni aggiuntive da parte del fruitore. Grazie alla sua segnalazione abbiamo aggiornato anche le line guida all'implementazione degli e-service sulla specifica 1.3.1 UNIAFAM

**Comment by nicolabeghin** [comment]
@andreapoli c'è una motivazione specifica per cui togliendo la parte di audit dalle API 
![image](https://github.com/user-attachments/assets/5d485a71-3244-4d66-8fdd-f2d14850780f)
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/e840977c-1d71-4481-a9dc-e3a08fec513c">

le erogazioni collegate non funzionano più in quanto mancanti della sezione "Profilo interoperabilità" ModI?

PRIMA
<img width="1162" alt="image" src="https://github.com/user-attachments/assets/bc30e48e-9a24-4294-bd44-40487a6f1022">

DOPO
<img width="1167" alt="image" src="https://github.com/user-attachments/assets/21aadaf2-690d-45da-8ac8-071aad9f82a3">

grazie

**Comment by andreapoli** [comment]
Buongiorno @nicolabeghin.

Utilizzando solo il pattern 'ID_AUTH_REST' con la Generazione Token 'PDND', tutte le informazioni necessarie per validare l'unico token atteso, il voucher della PDND, risiedono nella Token Policy. Per questo motivo, la sezione 'ModI' nell'erogazione non è più disponibile.

Pertanto, il comportamento che hai rilevato è quello previsto. Non ho però capito se, a seguito della modifica, stai riscontrando errori nelle chiamate e, in tal caso, quale errore viene riportato nei diagnostici della transazione.

**Comment by andreapoli** [comment]
@nicolabeghin, hai seguito perfettamente quanto indicato nella sezione [Erogazione ID_AUTH_REST_01 (PDND)](https://govway.org/documentazione/console/profiloModIPA/messaggio/idar01/pdnd/pdnd_erogazione.html), soprattutto per quanto riguarda la 'Verifica Audience'.
