### ISSUE TITLE
Dinamicità sul Connettore File in base al valore di un header

### ISSUE THREAD

**Issue by andreapoli** [link-it/govway#17]
La richiesta descritta nell'issue #15 evidenzia l'utilità di estendere le informazioni dinamiche utilizzabili nel connettore di tipo 'file' anche rispetto agli header http della richiesta in uscita.
Ad esempio un nome di un file potrebbe essere dichiarato come segue: '/tmp/{header:<NOME-HEADER>}.xml'

Valutare anche la possibilità di utilizzare i valori di un parametro della query, e le proprietà specifiche di protocollo della Busta.

**Comment by marcomarsala** [comment]
Mi sembra però che non sia possibile posizionare le fatture ricevute e le notifiche ricevute in cartelle diverse, in base al codice destinatario usato (ne ho 100). Mi sembra che il codice destinatario si trovi solo nel file XML dei metadati, che viene inviato da SDI come stringa codificata in base64 all’endpoint `RicezioneFatture`,  tramite l’attributo `Metadati` (codifica base64) dell’operazione `fileSdiConMetadati`, corretto? Potrebbe essere utile riuscire tramite `{header:}` a leggere anche nelle stringhe XML e base64.

**Comment by andreapoli** [comment]
GovWay effettua esattamente quello che hai descritto e cioè decodifica le informazioni presenti nel base64 dei Metadati e le mette a disposizione tramite header http.

Le fatture ricevute le puoi memorizzare in cartelle differenti, in base al codice destinatario, usando il seguente path:
- /tmp/{header:GovWay-SDI-CodiceDestinatario}/{header:GovWay-SDI-NomeFile}

Per quanto riguarda invece le notifiche, l'informazione sul codice destinatario non è presente ne tra le informazioni del protocollo sdi ne all'interno della notifica (codificata in base64 all'interno dell'operazione 'NotificaDecorrenzaTermini').

**Comment by marcomarsala** [comment]
Grandioso. Si in effetti per le notifiche delle fatture inviate il codice destinatario non ha senso, perché potrei essere accreditato solo per l’invio e non averlo.

Sto cercando di fornire accesso a due programmi distinti tramite la stessa istanza di GovWay. A ogni programma ho assegnato un diverso codice destinatario, e ogni programma dovrebbe vedere solo le notifiche per le fatture che invia. Ogni programma ha le sue credenziali su GovWay per inviare. Per la ricezione il problema è già risolto come mi hai indicato. Ma per l’invio? Non ho modo di smistare le notifiche all’utente che ha inviato la fattura? Devo necessariamente mettere uno script a valle che le smistino c’è un altro modo?

**Comment by andreapoli** [comment]
Nella fatturazione attiva, l'informazione sull'utente che ha inviato la fattura non è presente all'interno delle notifiche e quindi non puoi utilizzare la soluzione precedentemente riportata.

Potresti però riconciliare la fattura inviata e le notifiche ricevute sotto una stessa directory rappresentata dall'identificativo generato dallo SDI.

Durante l'invio di una fattura tale identificativo ti viene ritornato nell'header http della risposta:
-  'GovWay-SDI-IdentificativoSdI'

Durante la ricezione di una notifica potresti utilizzare il path dinamico:
- /tmp/{header:GovWay-SDI-IdentificativoSdI}/{header:GovWay-SDI-NomeFile}

**Comment by marcomarsala** [comment]
Grazie, ma così facendo dovrei comunque dare accesso a /tmp/ a entrambi i programmi, quindi ogni programma vedrebbe anche le notifiche per le fatture inviate dall’altro.

**Comment by marcomarsala** [comment]
Quello che vorrei fare è consentire a due aziende diverse di inviare e ricevere fatture e notifiche tramite GovWay. 

Sull’invio non ci sono difficoltà.

In ricezione, ogni azienda dovrebbe avere accesso solo alle sue fatture passive e alle notifiche dei suoi invii, senza potere accedere ai dati dell’altra. Ogni azienda utilizza un codice destinatario differente. Al momento salvo le fatture su disco con il connettore file, ma non è un requisito.

C’è modo di effettuare questo smistamento a livello di GovWay? Oppure devo necessariamente passarle ad un mio script che le separi?

**Comment by andreapoli** [comment]
Non vi è un modo per riconciliare le notifiche e le fatture rispetto al codice destinatario senza mantenere uno stato poichè tale codice non è presente in tutte le notifiche. Servirebbe una mappa che "traduca" l'identificativo sdi nel codice destinatario associato.
GovWay invece gestisce ogni comunicazione in maniera stateless.

Le soluzioni sono quindi quelle da te indicate.

**Comment by andreapoli** [comment]
La riconciliazione tra identificativo SDI e Codice Destinatario può in effetti essere realizzata,  senza dover introdurre uno stato, accedendo alle tracce emesse da GovWay.

Per questo motivo abbiamo deciso di aggiungere tale funzionalità (#27 ) nella prossima release.

Con la prossima release potrai quindi smistare anche le notifiche utilizzando il path dinamico:
- /tmp/{header:GovWay-SDI-CodiceDestinatario}/{header:GovWay-SDI-NomeFile}

**Comment by marcomarsala** [comment]
Fantastico! Per quanto riguarda le fatture attive e relative notifiche, è possibile riconciliarle in base all’Applicativo che le ha inviate? Infatti, ogni azienda ha le proprie credenziali su GovWay per effettuare l’invio.
