### ISSUE TITLE
Impossibile validare Header JWT (RFC 9068) rilasciato dalla PDND

### ISSUE THREAD

**Issue by angeloS-98** [link-it/govway#170]
Salve, facendo qualche test durante l'esposizione di un servizio in erogazione abbiamo riscontrato un problema dovuto alla fase di validazione dei JWT. La validazione avviene tramite la Token Policy PDND (built-in) nella quale è stata abilitata anche la validazione dell'Header seguendo quanto riportato nel manuale operativo della PDND per la validazione dei voucher.

**Descrizione del Bug**
Abilitando la validazione dell'Header nella Token Policy di Validazione PDND (Formato del Token **RFC 9068**)  e inserendo i valori attesi per i claim _typ_ e _alg_, come specificato sia nella RFC di riferimento che nel manuale operativo, l'applicativo risponde lato erogazione con il messaggio: _"Gestione Token Fallita (401)"_, ripreso dalla console di monitoraggio. 
Dettaglio errore: _"Validazione del token 'JWS' fallita: Token non valido: JWT header validation failed; Expected claim 'cty' not found"_

**Come riprodurlo:**
1. Definire un'API con profilo **ModI** e abilitare la Generazione Token tramite _Authorization PDND_.
1. Definire un'erogazione di un e-service su GovWay con profilo **ModI** per l'API precedentemente definita.
1. Lato erogazione abilitare il **Controllo degli Accessi** con _Autenticazione Token_, policy PDND. I parametri impostati per la validazione dell'Header JWT sono:
	- typ: at+jwt
	- cty: 
	- alg: RS256

**Risultato atteso:**
Validazione del token JWT completata con successo in quanto il campo 'cty' non è obbligatorio e il token rilasciato dalla PDND effettivamente non presenta tale campo.

**Screenshots:**

Configurazione Profilo di Interoperabilità ModI API:
![Configurazione Profilo di Interoperabilità ModI API](https://github.com/user-attachments/assets/506ddff5-6051-435d-9dbf-de820e804072)

Controllo degli Accessi Erogazione:
![Controllo degli Accessi Erogazione](https://github.com/user-attachments/assets/eaf2ddc3-3897-4f3f-b7df-5e9aea4f222d)

Token Policy PDND con Validazione JWT Header:
![Token Policy PDND con Validazione JWT Header](https://github.com/user-attachments/assets/0971fb9f-6db9-42b4-b721-71f82311a70b)

Dettaglio Errore Console di Monitoraggio:
![Dettaglio Errore Console di Monitoraggio](https://github.com/user-attachments/assets/694c93c6-f2fa-4539-9006-63667be9f7f6)

**Ambiente:**
 - OS: CentOS 7
 - Browser: Chrome 127
 - GovWay: 3.3.14
 - AS: WildFly Full 26.1.3 (Final) 
 - Java: OpenJDK 11
 - DBMS: Oracle 19c

**Note aggiuntive:**
Le prime volte in cui verificavamo l'errore, inoltre, il dettaglio dell'errore riportato dalla console di monitoraggio presentava il seguente messaggio: _"Validazione del token 'JWS' fallita: Token non valido: JWT header validation failed; null"_, non intercettando bene l'eccezione lanciata per qualche strano motivo.

Allego screenshot di seguito:
![Monitor_Dettaglio_Errore_null](https://github.com/user-attachments/assets/939922e6-1e61-4948-8761-1827767d5388)

**Comment by andreapoli** [comment]
Buonasera @angeloS-98 

Per replicare il problema avremmo bisogno di:
- i file di log (govway_core.log) contenenti i 2 errori che hai riportato nell'issue;
- la token policy 'PDND' che state utilizzando. Per inviarcela dovresti selezionarla dall'elenco, cliccare sul pulsante 'Esporta' in basso e allegare l'archivio zip prodotto all'issue.

**Comment by angeloS-98** [comment]
Buongiorno @andreapoli,

Grazie per la risposta. Allego subito i file richiesti.

- Token Policy PDND: [TokenPolicy_PDND.zip](https://github.com/user-attachments/files/16520451/TokenPolicy_PDND.zip)
- Log di errore: [govway_core.log](https://github.com/user-attachments/files/16520452/govway_core.log)

Per quanto riguarda le log, ho esportato il file e mantenuto soltanto gli errori relativi ai due messaggi riportati negli screen, in modo da rendere più rapida la lettura ed evitando altri errori, come suggerito.

Per completezza, abbiamo anche provato l'erogazione con le stesse modalità indicate precedentemente, ma disabilitando lato Token Policy PDND la validazione dell'header JWT, e il tutto funziona correttamente.

**Comment by andreapoli** [comment]
Grazie  @angeloS-98,
l'anomalia è stata riprodotta e risolta nel commit https://github.com/link-it/govway/commit/f21f95dd7ee01098b815bd26e6924000b5788a0a e sarà inclusa nella prossima versione rilasciata.
