### ISSUE TITLE
Traccia di una precedente fattura inviata [...] non rilevata

### ISSUE THREAD

**Issue by kenayagi** [link-it/govway#171]
Buongiorno.

Una breve premessa: sto testando GovWay 3.3.15 in ambiente Docker, con l'obiettivo di adottarlo come interfaccia verso SdI per invio e ricezione di fatture elettroniche da un ERP open-source ( Odoo #164 ).

Sto attualmente effettuando i Test di Interoperabilità con il Sistema di Interscambio.

Ho notato nei log Diagnostici che nella fase di Sbustamento:

```
La validazione ha rilevato 1 eccezioni di rilevanza non grave:
Eccezione INFO con codice [GOVWAY-5] - EccezioneValidazioneProtocollo: Traccia di una precedente fattura inviata, con identificativo SDI [29549428], non rilevata: Errore durante la ricerca del datasource...
```

Avete suggerimenti su come correggere la configurazione?

**Comment by kenayagi** [comment]
Ciao @andreapoli 

Ecco qui i [log di GovWay](https://github.com/user-attachments/files/16851983/govway_log.zip).

Sto usando Tomcat incluso nell'immagine Docker, per cui i log dovrebbero essere nello stesso ZIP qui sopra.
Se ho frainteso, potresti spiegarmi meglio a cosa ti riferisci con "log dell'application server"?

Grazie! 😊

**Comment by andreapoli** [comment]
Buongiorno @kenayagi 

I log che ci hai inviato sono sufficienti per effettuare l'analisi. Come indicato anche da te, includono i log di Tomcat (catalina.*.log).

L'errore che hai riscontrato è un'anomalia che si verifica quando si utilizza Tomcat come application server. Questa problematica è emersa a partire dalla versione 3.3.15 dell'[immagine Docker](https://hub.docker.com/r/linkitaly/govway), dove l'application server di base è stato modificato da WildFly 26.1.3 a Tomcat 9.0.91, come indicato nelle [note di rilascio](https://hub.docker.com/r/linkitaly/govway).

Il problema verrà risolto nella prossima versione. Nel frattempo, puoi adottare come workaround la creazione di un file _sdi_local.properties_ all'interno della directory di configurazione _/etc/govway_, montata in un volume esterno. Il file deve contenere la seguente proprietà:
`org.openspcoop2.protocol.sdi.tracce.dataSource=java:/comp/env/org.govway.datasource`

**Comment by andreapoli** [comment]
Buongiorno @kenayagi 

Il workaround suggerito dovrebbe funzionare, poiché abbiamo replicato l'anomalia da te riscontrata e l'abbiamo risolta attraverso la soluzione fornita.

Puoi confermarmi:
- di aver creato il file _sdi_local.properties_ all'interno della directory di configurazione _/etc/govway_, montata su un volume esterno (ad esempio tramite opzione docker `-v ~/govway_conf:/etc/govway`)
- di aver riavviato il container dopo aver creato il file

**Comment by kenayagi** [comment]
Ciao @andreapoli

Chiedo venia: avevo aggiunto la proprietà al file _govway_local.properties_ anziché al _sdi_local.properties_. 😑😑😑
L'avviso ora non si presenta più.

Grazie!
