### ISSUE TITLE
Dump raw della risposta in ingresso alla PdD (SPCoop)

### ISSUE THREAD

**Issue by falbesano** [link-it/govway#175]
Buongiorno a tutti,

ho un errore di cui non riesco a venire a capo...
Usando GovWay per l'interazione con il Registro Imprese, per alcuni invii abbiamo un errore loggato sulla console di monitoraggio (e ritornato al chiamante):

Riscontrato errore durante l'inoltro del Messaggio di cooperazione con identificativo [xxxxxxxxxxxxxxxxxxxxxxxxxxSPCoopIT_0001519_2024-10-11_15:56] inviato alla parte destinataria [spc/UICCIAAPortaleImprese] mediante connettore [http] (location:[ https://UICCIAAPortaleImprese.camcom.gov.it/pdd/servizi](https://uicciaaportaleimprese.camcom.gov.it/pdd/servizi)): Errore avvenuto durante la consegna HTTP: Non è stato possibile comprendere come trattare il messaggio ricevuto (Content-Type: text/html; charset=utf-8): Header Content-Type definito nell'http reply non è tra quelli conosciuti: text/xml

Mi pare di capire che il WS del RI risponda con un errore html al posto di una risposta SOAP, ma non riesco in nessun modo a vedere la traccia completa per capire di che errore si tratta. Ho abilitato tutti i possibili Tracciamenti  nella configurazione, ma non riesco a vedere il raw della risposta in ingresso...

![pV8woLlvOJrrWs2d](https://github.com/user-attachments/assets/29c7df0c-287b-43cb-a0f6-3ee03b905279)

Esiste un modo per loggare la risposta dell'altra PdD, anche se questa non è un SOAP valido?

Grazie 1000 e buona giornata
Federico

**Comment by andreapoli** [comment]
Buonasera @falbesano 

nelle ultime versioni l'eventuale risposta HTML viene riportata direttamente nel messaggio diagnostico e quindi nella prima pagina di dettaglio della transazione:

![Screenshot from 2024-10-14 15-47-51](https://github.com/user-attachments/assets/f50cc8ef-fc73-49b4-94c0-2ff82606c4d6)

In alternativa puoi utilizzare la funzionalità [debug](https://govway.org/documentazione/console/avanzate/connettori/debug.html) attivabile direttamente sul connettore utilizzando la console in [modalità avanzata](https://govway.org/documentazione/console/avanzate/modalita_avanzata.html) per esaminare tutto il tracciato della chiamata.

**Comment by falbesano** [comment]
Grazie 1000, impostando il debug nel connettore ho poi trovato il log che cercavo direttamente nella traccia:
![immagine](https://github.com/user-attachments/assets/100d4a78-de46-4ba5-9f17-b639761fb352)
