### ISSUE TITLE
Autenticazione [ssl] fallita endpoint TrasmissioneFatture

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#18]
Quando l'ambiente di test SdI tenta di inviarmi una notifica, trovo in GovWayMonitor il seguente errore:

`Autenticazione [ssl] fallita : Autenticazione fallita, credenziali non fornite`

In allegato l'esportazione dei diagnostici: [Diagnostici.zip](https://github.com/link-it/govway/files/2677026/Diagnostici.zip)

![image](https://user-images.githubusercontent.com/5349718/49955775-f712f680-ff03-11e8-8a85-22d54bac23a5.png)

Che cosa significa?

**Comment by andreapoli** [comment]
L'erogazione del Servizio 'TrasmissioneFatture' viene configurata dalla govlet con autenticazione https abilitata per default. Tale configurazione puoi riscontrarla accedendo alla maschera relativa al 'Controllo degli Accessi' tramite la Configurazione dell'erogazione 'TrasmissioneFatture'. 

In caso l'autenticazione sia abilitata ed impostata ad 'https' GovWay deve ricevere il certificato client validato dal tuo frontend https.

Se hai configurato una porta https direttamente sull'application server (wildfly o tomcat) verifica di aver impostato l'opportuna opzione, ad esempio:
- wildfly: verify-client="REQUIRED" oppure verify-client="REQUESTED" sul https-listener
- tomcat: clientAuth="true" sul Connector https

Se invece utilizzi un frontend http (Apache httpd, IIS, etc) per la terminazione ssl fai riferimento a quanto indicato nella sua documentazione ufficiale.

**Comment by marcomarsala** [comment]
Il certificato è sul front-end nginx. Vedo che il controllo accessi non è disattivavile, faccio delle prove.

**Comment by marcomarsala** [comment]
Si, mi è utile per fare delle prove veloci in attesa di configurare bene il tutto. Eliminando il soggetto non cambia nulla (endpoint, etc..)?

**Comment by andreapoli** [comment]
Il soggetto viene eliminato solamente dalla lista di quelli autorizzati per il servizio 'Trasmissione Fatture'. 
Non perdi alcuna configurazione relativa al connettore, endpoint etc...

**Comment by marcomarsala** [comment]
Fatto. Comunque ho visto come configurare nginx, ma quale certificato deve inviare a GovWay? Dato il contenuto del campo Subject del soggetto CentroServiziFatturaPA, suppongo SistemaDiInterscambioFatturaPA.cer?

**Comment by marcomarsala** [comment]
Fatto. Comunque ho visto come configurare nginx, ma quale certificato deve inviare nginx a GovWay?

**Comment by andreapoli** [comment]
Il Certificato Client utilizzato dallo SDI quando ti invia le notifiche.
Il Subject di tale certificato deve corrispondere a quello indicato nel campo Subject del Soggetto CentroServiziFatturaPA.
