### ISSUE TITLE
Chiarimenti Rate Limiting per Erogazione

### ISSUE THREAD

**Issue by angeloS-98** [link-it/govway#183]
Salve,
stiamo testando la parte di erogazione dei servizi, in particolare la configurazione del rate limiting per le richieste in ingresso.
Vorremo impostare due diversi Rate Limiting che vadano a rispettare le soglie definite durante la pubblicazione dell'eservice sulla piattaforma PDND; nello specifico:
- una policy generale sul **_limite di richieste totali giornaliere_**;
- una policy specifica sul **_limite di richieste giornaliere per finalità_** (quindi per Purpose ID).

Consultando la documentazione, in particolare al link [Rate Limiting - Attivazione Nuova Policy](https://govway.org/documentazione/console/profiloApiGateway/rateLimiting/attivazioneNuovaPolicy.html), e facendo delle prove, non riusciamo a capire come poter specificare un Raggruppamento per PurposeId (_punto 2_). 

Di seguito allego le configurazioni provate per le due diverse policy che vorremmo definire.

_**Punto 1**_:
![Rate Limiting richieste totali giornaliere](https://github.com/user-attachments/assets/04feeeca-0417-46e2-8f50-6f8be7a8966e)

**_Punto 2_**:
![Rate Limiting richieste giornaliere per clientId](https://github.com/user-attachments/assets/2ce5a6f1-c322-4d65-ba5a-70f02fec9bc3)

Per prima cosa vorremmo chiedere conferma che la policy al _punto 1_ rispetti la configurazione attesa. Mentre, per quanto riguarda la policy al _punto 2_ non capiamo se è possibile specificare come raggruppamento il purposeId e, se possibile, vi chiederemmo aiuto in merito.

In alternativa, avevamo anche visto che fosse possibile definire dei plugin personalizzati che vadano a definire una specifica classe che estenda l'interfaccia IRateLimiting, come spiegato nella documentazione al link: [Rate Limiting - Filtro/Raggruppamento personalizzati](https://govway.org/documentazione/console/configurazione/rateLimiting/filtriRaggruppamentiPersonalizzati.html).
Anche in questo caso, però, non riusciamo a trovare qualche esempio più dettagliato per capire meglio come poter implementare la classe personalizzata e come poterla poi caricare su GovWay. Avete qualche esempio da cui poter partire per tentare questo approccio?

Grazie in anticipo per l'aiuto!

**Comment by andreapoli** [comment]
Buongiorno @angeloS-98 .

Immagino ti riferisci alle seguenti quote richieste dalla PDND:

![image](https://github.com/user-attachments/assets/d0663316-7ee6-43b7-9115-13203c20b504)

La policy che avete definito al prima punto limita correttamente il numero di richieste totali giornaliere.

Per quanto concerne la soglia per fruitore un raggruppamento per purposeId non è quanto richiesto dalla PDND; per effettuare un conteggio della soglia per fruitore bisogna raggruppare per clientId:

![image](https://github.com/user-attachments/assets/0b41f493-1b08-4f07-87a1-dc996fb8cf7c)

Attenzione infine a definire le 2 policy nell'ordine corretto in modo che la verifica del carico globale consenta di proseguire l'elaborazione delle policy di rate limiting rispetto al controllo della quota fruitore.  Per attivare questo comportamento la voce 'Elaborazione' della policy 'Carico Globale' deve essere impostata alla voce 'prosegui' .

![image](https://github.com/user-attachments/assets/08d27041-9fd4-4ed3-b500-10d97f356faf)

Di seguito un esempio dell'ordine delle due policy e dei criteri di elaborazione a loro associati per implementare i controlli richiesti dalla PDND:

![image](https://github.com/user-attachments/assets/d9844848-91d1-450a-a161-79a44427ad73)

**Comment by andreapoli** [comment]
Un conteggio analogo, basato sull'organizzazione proprietaria del clientId, può essere eseguito seguendo le istruzioni fornite nella sezione [Politiche di Rate Limiting basate su informazioni prelevate via API PDND](https://govway.org/documentazione/console/profiloModIPA/messaggio/avanzata/pdndRateLimiting.html#modipa-sicurezza-avanzate-pdndratelimiting) della documentazione.

In questo contesto, il calcolo viene effettuato utilizzando le informazioni relative all’organizzazione, ottenute interrogando le API della PDND. Eventuali clientId differenti, appartenenti alla medesima organizzazione, sono inclusi nel medesimo conteggio.

La funzionalità è disponibile a partire dalla versione [3.3.15](https://govway.org/documentazione/releaseNotes/3.3.15/modipa.html).

**Comment by angeloS-98** [comment]
Grazie @andreapoli, sei stato chiarissimo e gentilissimo come sempre.

A che ci sono vorrei chiederti giusto dei chiarimenti per il discorso riguardo le soglie richieste dalla PDND perché probabilmente le abbiamo interpretate in modo leggermente diverso.
- Per quanto riguarda quella generale, è la soglia di richieste giornaliere totali, quindi di tutti i fruitori, e a tal punto non capisco bene perché settarla per proseguire l'elaborazione e non bloccarla.
- Per quella legata ai singoli fruitori, invece, pensavamo fosse legata alla finalità definita dal soggetto fruitore e non dal client in uso, in quanto in teoria potrei fruire dello stesso servizio per finalità diverse.

Sono giusto dei chiarimenti per non incappare nuovamente in qualche errore, ma già gli esempi di prima ci aiutano a risolvere il problema. Chiudo anche la issue a tal proposito!

**Comment by andreapoli** [comment]
> * Per quanto riguarda quella generale, è la soglia di richieste giornaliere totali, quindi di tutti i fruitori, e a tal punto non capisco bene perché settarla per proseguire l'elaborazione e non bloccarla.

Il fatto di proseguire serve a far valutare a GovWay la prossima policy quando quella generale è soddisfatta. Trovi maggiori indicazioni sull'algoritmo di valutazione delle policy nella sezione [Criteri di valutazione delle policy](https://govway.org/documentazione/console/profiloApiGateway/rateLimiting/criteriValutazione.html#ratelimiting-criterivalutazione).
