### ISSUE TITLE
Quickstart con docker-compose.yml

### ISSUE THREAD

**Issue by ioggstream** [link-it/govway#2]
## Desiderata

Un docker-compose.yml che permetta di testare al volo il gateway.

**Comment by andreapoli** [comment]
Lo predisponiamo per la nuova versione 3.0.1 che stiamo rilasciando in questi giorni, ti faccio sapere appena disponibile.

**Comment by ioggstream** [comment]
@andreapoli ottimo, resto in attesa allora. OT: è possibile pilotare il vostro gateway tramite API?

**Comment by andreapoli** [comment]
> resto in attesa allora. OT: è possibile pilotare il vostro gateway tramite API?

@ioggstream al momento abbiamo solo le API SOAP ereditate dalla precedente versione
(OpenSPCoop v2), ma sono inadatte per i nuovi scenari.

Stiamo lavorando alle nuove [API](https://github.com/link-it/GovWay/tree/3.0.rsApi/tools/rs/config/server/src/schemi/govway_rs-api_config.yaml) sul branch '3.0.rsApi'. 
Ti faccio sapere non appena avremo completato l'adeguamento dell'interfaccia alle linee guida indicate nell'[api-starter-kit](https://github.com/teamdigitale/api-openapi-samples/blob/master/openapi-v3/schema/components.yaml), così se puoi ci dai un feedback.

**Comment by ioggstream** [comment]
@andreapoli considera che:

  - le linee guida *messe in consultazione* sono queste https://lg-modellointeroperabilita.readthedocs.io/it/latest/
  - lo starter-kit è un oggetto utile ad iniziare il lavoro ma è comunque work-in-progress.
    La parte di header 429 e 503 è invece più consolidata

**Comment by andreapoli** [comment]
@ioggstream conosco bene le linee guida da te citate.
Per lo starter-kit ti posso dire che in @link-it/devo i work-in-progress ci piacciono :-)

**Comment by ioggstream** [comment]
Ottimo! Speriamo di rilasciare presto il prossimo capitolo che dovrebbe contenere un dettaglio su rest - tutto nuovo - e soap.

Issue e PR sui repo del modi2018 e dello starter kit sono benvenuti

**Comment by andreapoli** [comment]
Stiamo realizzando una [QuickStart Guide](https://github.com/link-it/govway/blob/master/resources/doc/pdf/GovWay-GuidaRapida.pdf) che descrive i principali casi d'uso di GovWay.
Puoi utilizzarla come riferimento per orientarti velocemente sulle funzionalità del prodotto e provarle rapidamente con [govway-docker](https://github.com/link-it/govway-docker).

Tieni presente che è ancora un work in progress e quindi troverai sezioni in 'TO DO'.
L'indice permette comunque di comprendere quali siano tutte le funzionalità supportate dal gateway.

**Comment by andreapoli** [comment]
Le versioni rilasciate di GovWay sono disponibili su [DockerHub](https://hub.docker.com/r/linkitaly/govway).

Il progetto [govway-docker](https://github.com/link-it/govway-docker) fornisce tutto il necessario per produrre un'ambiente di prova per GovWay funzionante, containerizzato in formato Docker, a partire dai sorgenti.
