### ISSUE TITLE
New references to teamdigitale schemas

### ISSUE THREAD

**Issue by ioggstream** [link-it/govway#21]
@andreapoli we're currently working to version our OAS3 references. 

see https://github.com/teamdigitale/openapi/pull/2

https://github.com/link-it/govway/blob/a6efa30fa53fe36d3a73586fe2468ad3adf6cd09/tools/rs/config/server/src/schemi/teamdigitale-components.yaml#L9

**Comment by andreapoli** [comment]
Integrato in govway lo schema aggiornato [definitions.yaml](https://github.com/teamdigitale/openapi/blob/master/docs/definitions.yaml).

Lo schema risiede in [tools/rs/core/schemi/teamdigitale-openapi_definitions.yaml](https://github.com/link-it/govway/blob/master/tools/rs/core/schemi/teamdigitale-openapi_definitions.yaml)
