### ISSUE TITLE
Use maven-dependency-check from owasp

### ISSUE THREAD

**Issue by ioggstream** [link-it/govway#22]
## I wish

A maven dependency validator, eg. https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html

Integrated in the CI too.

**Comment by andreapoli** [comment]
Effettuata integrazione di GovWay in continuous integration tramite jenkins:
- https://jenkins.link.it/job/GovWay/

E' stato creato un pipeline che attua i seguenti step:
- Verifica le dipendenze tramite il check [owasp](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html)
- Verifica la compilazione dei sorgenti
- Produce l'archivio 'tar.gz' contenente l'installer della versione binaria e lo esegue.
- Effettua il deploy degli archivi e datasource prodotti dall'installer su tomcat
- Carica gli script sql prodotti dall'installer su un nuovo database postgresql inizializzato al momento.
- Esegue una batteria di test (TestNG) relativa alle classi base del progetto (org.openspcoop2.utils e org.openspcoop2.pdd)
- Esegue i test di integrazione per quanto concerne il profilo 'API Gateway
- Esegue i test di integrazione per quanto concerne il profilo 'SPCoop'

Al termine dell'esecuzione del pipeline vengono pubblicati:
- Risultati delle eventuali vulnerabilità riscontrate relative alle dipendenze (sezione 'Vulnerability Trend')
- Risultati dei test (sezione 'TestNG Results Trend')
