### ISSUE TITLE
Integrazione di GovWay con sistemi di firma automatica 

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#23]
GovWay fornisce qualche strumento per integrarsi con le API di sistemi di Firma Automatica Massiva (per esempio quella di Aruba PEC) oppure è necessario firmare i file a monte?

**Comment by andreapoli** [comment]
E' necessario firmare le fatture prima di inoltrarle a GovWay.

GovWay, nel profilo 'Fatturazione Elettronica', semplifica l'interazione con lo SDI permettendo ad un applicativo di inoltrare e/o ricevere fatture/notifiche (firmate)  senza doversi preoccupare dell'imbustamento nel protocollo sdicoop e della gestione MTOM. La creazione/gestione/firma delle fatture viene invece lasciata interamente a carico dell'applicativo.
