### ISSUE TITLE
Incompatibilità con MySQL  5.6.x

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#24]
Le versioni 3.0 e 3.0.1 non possono essere installate su MySQL in quanto importando il database con il comando `mysql -ugovway -p govway < sql/GovWay.sql` si ottiene questo errore:

`ERROR 1071 (42000) at line 546: Specified key was too long; max key length is 767 bytes`

Il limite indicato sembra non essere incrementabile se non modificando un altro row format (che richiede una modifica dello script SQL di inizializzazione): https://dev.mysql.com/doc/refman/8.0/en/create-index.html

**Comment by andreapoli** [comment]
Si tratta di un problema noto della versione 3.0.0, poi risolto nella versione 3.0.1 (vedi fix in data '2018-10-19' nel [ChangeLog](https://github.com/link-it/govway/blob/master/ChangeLog).
Gli script sql generati dalla 3.0.1 contengono nella descrizione di ogni tabella anche la definizione del row format 'ROW_FORMAT DYNAMIC'.

Verifica di aver utilizzato lo script sql generato dall'installer della versione 3.0.1 (verificando la presenza del raw format dynamic).
Se continui a riscontrare l'errrore dovresti allegare all'issue lo script sql generato ed indicarci la versione esatta di MySQL che stai utilizzando in modo da poter replicare il problema.

**Comment by andreapoli** [comment]
Sei riuscito ad utilizzare il file 'GovWay.sql' per mysql prodotto dalla versione 3.0.1 ? 

Se continui a riscontrare l'errrore pui allegarci lo script sql generato ed indicarci la versione esatta di MySQL che stai utilizzando in modo da poter replicare il problema?

**Comment by marcomarsala** [comment]
Su una nuova installazione, effettuata su macchina con MySQL 5.7.25 non si presentano problemi. Appena mi ridanno alla macchina su cui avevo riscontrato il problema riprovo.

**Comment by marcomarsala** [comment]
Confermo che su MySQL 5.6.42 il problema persiste: `ERROR 1071 (42000) at line 546: Specified key was too long; max key length is 767 byte`.

Allego il file generato dall'installer della versione 3.0.1: [GovWay.zip](https://github.com/link-it/govway/files/3032585/GovWay.zip)

Il comando eseguito è: `mysql -uroot -p test < sql/GovWay.sql`

**Comment by andreapoli** [comment]
Dalla versione 3.0.1 gli script sql contengono nella descrizione di ogni tabella anche la definizione del row format 'ROW_FORMAT DYNAMIC'. Il motivo risiede nella possibilità di avere indici fino a 3072 bytes.

Anche la versione di mysql 5.6.42 supporta tale formato come indicato nella [documentazione](https://dev.mysql.com/doc/refman/5.6/en/innodb-row-format.html#innodb-row-format-dynamic) ma richiede che la variabile globale 'innodb_large_prefix' sia abilitata mentre per default è disabilitata.
L'abilitazione richiede a sua volta l'impostazione di altre variabili globali riportate di seguito:

SET GLOBAL innodb_large_prefix=ON;
SET GLOBAL innodb_file_format=barracuda;
SET GLOBAL innodb_file_per_table=true;

Se imposti queste variabili il caricamento va a buon fine.

Quanto premesso dalla nuova versione GovWay richiederà una versione di MySQL >= 5.7.8.
