### ISSUE TITLE
Documentazione opzioni "Sbustamento SOAP" e "Sbustamento SDI"

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#25]
Non le trovo nel Manuale Utente di GovWay o dei GovLet.

**Comment by andreapoli** [comment]
Si tratta di due configurazioni disponibili, nel connettore di una erogazione, solamente se la console di gestione viene utilizzata in modalità "avanzata".
Indicano come inoltrare all'applicativo interno al dominio il messaggio SOAP ricevuto dallo SDI:

- Sbustamento SOAP: se viene abilitata questa opzione verrà consegnato solamente l'xml interno al SOAP Body.
- Sbustamento SDI:  se l'opzione non è abilitata all'applicativo verrà consegnato il messaggio previsto dal protocollo [SDICoop](https://www.fatturapa.gov.it/export/fatturazione/it/normativa/f-3.htm) contenente al suo interno la fattura o la notifica codificata in base64. Se invece viene abilitata all'applicativo viene consegnata la fattura/notifica estratta dal messaggio e decodificata.

Le Govlet che hai utilizzato per configurare GovWay, sia per la [Fatturazione Passiva](https://github.com/link-it/govway/blob/master/resources/doc/govlet/Fatturazione/Govlet_FatturaPA_FatturazionePassiva.pdf) che per la [Fatturazione Attiva](https://github.com/link-it/govway/blob/master/resources/doc/govlet/Fatturazione/Govlet_FatturaPA_FatturazioneAttiva.pdf), creano delle erogazioni che possiedono entrambe le opzioni abilitate al fine di consegnare agli applicativi gli xml delle fatture e delle notifiche ricevute dallo SDI.
