### ISSUE TITLE
Restituire risposta SDI nel body

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#26]
Buongiorno,

inviando una fattura tramite il seguente comando cURL:

```
curl -k -X POST -basic --user XXX:YYY
 --data-binary @IT01629370097_4BFL6.xml -H "Content-Type: application/pkcs7-mime
" "https://fe.thenetworksolution.it/govway/sdi/out/xml2soap/Nineproof/CentroServ
iziFatturaPA/SdIRiceviFile/1?Versione=FPA12&TipoFile=P7M&IdPaese=IT&IdCodice=XXX"
```

ottengo risposta vuota (la fattura risulta correttamente inviata dalla console di monitoraggio con codice HTTP 202).

Aggiungendo il parametro -i alla chiamata cURL vedo i seguenti header della risposta HTTP:

```
HTTP/1.1 100 Continue

HTTP/1.1 202 Accepted
Server: nginx
Date: Fri, 15 Mar 2019 09:58:38 GMT
Transfer-Encoding: chunked
Connection: keep-alive
GovWay-Provider-Type: sdi
GovWay-SDI-NomeFile: IT01629370097_00010.xml.p7m
GovWay-Message-ID: 4fa4afed-431c-43c7-a410-5ccf8143dd4b
GovWay-SDI-IdentificativoSdI: 530097703
GovWay-Service-Type: sdi
GovWay-Sender-Type: sdi
GovWay-Transaction-ID: 47d35ef2-f4ab-45a1-8b47-7f0d038e8f9e
GovWay-Service-Version: 1
GovWay-Provider: CentroServiziFatturaPA
GovWay-Action: RiceviFile
GovWay-SDI-DataOraRicezione: 2019-03-15T10:58:38.332+01:00
GovWay-Service: SdIRiceviFile
GovWay-Sender: Nineproof
```

E' possibile ottenere, invece del body vuoto, il messaggio XML inviato da SDI (che dovrebbe essere il file dei metadati, anche detto notifica MT)?

**Comment by andreapoli** [comment]
Quando invii una fattura sei nel flusso di [Fatturazione Attiva](https://www.fatturapa.gov.it/export/fatturazione/sdi/ws/trasmissione/v3.0/SDICoop_trasmissione_v3.0.pdf). Come puoi vedere dalla [specifica](https://www.fatturapa.gov.it/export/fatturazione/sdi/ws/trasmissione/v3.0/SDICoop_trasmissione_v3.0.pdf), nella risposta all'invio di una fattura (web service 'SdIRiceviFile') non è previtsto alcun messaggio XML ritornato dallo SDI ma solamente l'identificativo SDI assegnato al file trasmesso e la Date Ora di ricezione da parte dello SdI. Entrambe le informazioni sono ritornate negli header http che hai riportato.

La Notifica dei Metadati che richiedi è relativo al flusso di [Fatturazione Passiva](https://www.fatturapa.gov.it/export/fatturazione/sdi/ws/ricezione/v3.0/SDICoop_ricezione_v3.0.pdf).
