### ISSUE TITLE
Aggiunta del CodiceDestinatario tra le informazioni associate alle notifiche SDI

### ISSUE THREAD

**Issue by andreapoli** [link-it/govway#27]
La discussione intrapresa nell'issue #17 evidenzia l'utilità di estendere le informazioni SDI ritornate sotto forma di header HTTP da GovWay aggiungendo il Codice Destinatario tra le informazioni riportate per le notifiche.

L'informazione sul Codice Destinatario al momento della ricezione di una notifica è recuperabile accedendo alla traccia relativa al precedente invio o ricezione della fattura. 

L'aggiunta di tale informazione permetterà di poter realizzare la consegna smistando per codice destinatario proprio come richiesto  nell'issue #17,

**Comment by andreapoli** [comment]
Nella fatturazione attiva può essere utile riconciliare la fattura inviata con le successive notifiche ricevute utilizzando:

- IdTrasmittente (IdPaese + IdCodice)
- Applicativo che ha inviato la fattura 

Prevedere quindi di aggiungere anche tali informazioni recuperandole dalla traccia della fattura inviata.

**Comment by marcomarsala** [comment]
Fantastico. Così l'applicativo che ha inviato può accedere solo alle notifiche delle fatture che ha inviato. Mentre per la ricezione è tutto suddiviso in cartelle in base al codice destinatario su cui sono arrivate. Ottimo.

**Comment by andreapoli** [comment]
> La discussione intrapresa nell'issue #17 evidenzia l'utilità di estendere le informazioni SDI ritornate sotto forma di header HTTP da GovWay aggiungendo il Codice Destinatario tra le informazioni riportate per le notifiche.

Nella nuova versione sarà possibile utilizzare il seguente path dinamico per raggruppare le fatture e notifiche ricevute per Codice Destinatario:
- _/tmp/**${header:GovWay-SDI-CodiceDestinatario}**/${header:GovWay-SDI-NomeFile}_

Per raggrupparle ulteriormente per 'Identificativo SDI' è possibile aggiungere un livello al path:
- _/tmp/${header:GovWay-SDI-CodiceDestinatario}/**${header:GovWay-SDI-IdentificativoSdI}**/${header:GovWay-SDI-NomeFile}_

**Comment by andreapoli** [comment]
> Nella fatturazione attiva può essere utile riconciliare la fattura inviata con le successive notifiche ricevute utilizzando:
> 
> * IdTrasmittente (IdPaese + IdCodice)
> * Applicativo che ha inviato la fattura

Nella nuova versione sarà possibile utilizzare il seguente path dinamico per raggruppare le notifiche ricevute per Applicativo Mittente:
- _/tmp/${header:**GovWay-SDI-ApplicativoMittenteFattura**}/${header:GovWay-SDI-NomeFile}_ 

Con il seguente path invece è possibile raggruppare le notifiche per IdTrasmittente:
- /tmp/${header:**GovWay-SDI-DatiTrasmissione-IdTrasmittente-IdPaese**}${header:**GovWay-SDI-DatiTrasmissione-IdTrasmittente-IdCodice**}/${header:GovWay-SDI-NomeFile} 

Di seguito viene fornito un esempio di path dinamico che permette di collezionare le notifiche per ApplicativoMittente - IdTrasmittente- Identificativo SDI:
- /tmp/${header:GovWay-SDI-ApplicativoMittenteFattura}/${header:GovWay-SDI-DatiTrasmissione-IdTrasmittente-IdPaese}${header:GovWay-SDI-DatiTrasmissione-IdTrasmittente-IdCodice}/{header:GovWay-SDI-IdentificativoSdI}/${header:GovWay-SDI-NomeFile}
