### ISSUE TITLE
Console > Generale mostra errore dopo aggiornamento a 3.0.1

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#29]
Ho effettuato l'aggiornamento alla versione 3.0.1, ed ora la scheda Generale mostra il seguente messaggio di errore:

![image](https://user-images.githubusercontent.com/5349718/54810586-c1aa4180-4c86-11e9-909a-2351de436ddb.png)

Le altre schede sembrano funzionare correttamente.

**Comment by andreapoli** [comment]
Dovresti allegare il log prodotto dalla console (govway_console_core.log) per poter comprendere la problematica che riscontri.

**Comment by marcomarsala** [comment]
Allego il log. L'errore sembra essere: `Error :Non esiste un protocollo associato al tipo di soggetto [spc]`

[govway_console_core.log](https://github.com/link-it/govway/files/3032475/govway_console_core.log)

**Comment by andreapoli** [comment]
Il motivo dell'errore risiede nel fatto che sulla base dati è presente un soggetto con un profilo di interoperabilità non supportato dal software installato.

Quando è stato installata la versione 3.0.0, durante l'esecuzione dell'installer è stato selezionato il profilo di interoperabilità 'SPCoop'. Tale scelta ha fatto si che la base dati sia stata inizializzata con un soggetto di tipo 'spc'.
Tale profilo invece non è stato selezionato durante l'esecuzione dell'installer, della versione 3.0.1, in modalità di aggiornamento e questo ha comportato un disallineamento tra il software successivamente aggiornato e la base dati precedentemente inizializzata.

Per superare la problematica hai due opzioni:
- rieseguire l'installer, in modalità di aggiornamento, selezionando anche il profilo di interoperabilità 'SPCoop' ed eseguire un nuovo dispiegamento degli archivi generati.
- oppure, se nella versione 3.0.0, non avevi creato alcuna API tramite la console di gestione con profilo di interoperabilità 'SPCoop'  puoi utilizzare i seguenti comandi sql per eliminare il soggetto dalla base dati:
  - select id_connettore as IDCONNETTORE from soggetti where tipo_soggetto='spc';
  - delete from soggetti where tipo_soggetto='spc';
  - delete from connettori where id=IDCONNETTORE;

La maschera di selezione del profilo di interoperabilità nell'installer è la seguente:
![SceltaProfilo](https://user-images.githubusercontent.com/16049098/55399772-5ac13e00-554c-11e9-97bf-0cf73a369506.jpg)

Nella nuova versione aggiungeremo sia nell'installer, che nella guida di installazione, durante la modalità di aggiornamento, un'indicazione sul selezionare almeno i medesimi profili di interoperabilità scelti nella precedente versione.
