### ISSUE TITLE
Schermata Runtime mostra "Informazione non disponibile"

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#30]
Buongiorno,

su una nuova installazione della versione 3.0.1, la schermata Runtime si presenta con tutte le informazioni sostituite dalla scritta "Informazione non disponibile" e senza bottone per resettare la cache (sebbene risulti attiva in Generale):

![image](https://user-images.githubusercontent.com/5349718/55380419-68f96500-5520-11e9-930c-815d24100308.png)

**Comment by andreapoli** [comment]
Dovresti allegare il log prodotto dalla console (govway_console_core.log) per poter comprendere la problematica che riscontri.

Inoltre per replicare esattamente la tua installazione hai per caso effettuato configurazioni descritte nella sezione "Configurazione in Load Balancing" della [Guida di Installazione](https://github.com/link-it/govway/blob/master/resources/doc/pdf/GovWay-ManualeInstallazione.pdf) ? In tal caso dovresti allegare anche i file di proprietà 'govway_local.properties' e 'console_local.properties'.

**Comment by marcomarsala** [comment]
Il log è qui: https://github.com/link-it/govway/issues/29#issuecomment-478974111

Si tratta della medesima installazione, che la causa del problema sia la stessa?

**Comment by andreapoli** [comment]
> Si tratta della medesima installazione, che la causa del problema sia la stessa?

Si potrebbe tranquillamente essere riconducibile alla problematica indicata in #29.
Prova a seguire il workaround che ti ho indicato nel [commento](https://github.com/link-it/govway/issues/29#issuecomment-478974111).
Fammi sapere se il problema evidenziato in questo issue viene implicitamente risolto.

**Comment by marcomarsala** [comment]
Confermo che il workaround in #29 risolve anche questo problema.

**Comment by marcomarsala** [comment]
Ho un'altra installazione dove la schermata Runtime presenta questo problema. Non si tratta in questo caso del #29

**Comment by andreapoli** [comment]
Valgono le considerezioni indicate nel precedentemente [commento](https://github.com/link-it/govway/issues/30#issuecomment-478981837).
Dovresti allegare il log prodotto dalla console (govway_console_core.log) per poter comprendere la problematica che riscontri.

**Comment by marcomarsala** [comment]
Si trattava del medesimo problema di #32
