### ISSUE TITLE
Nomenclatura file

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#31]
GovWay può rinominare i file prima di inviarli allo SDI?

Abbiamo fatto delle prove inviando in HTTP POST dei file, senza passare il nome del file nella richiesta HTTP, e abbiamo notato che GovWay lo rinomina, incrementando correttamente il progressivo, ma non troviamo questa funzione nella documentazione.

Come possiamo fare a forzare il nome del file che vogliamo trasmettere? Ho provato ad includere nella richiesta HTTP POST, con la quale invio il file, gli header `Content-Disposition` e `GovWay-SDI-NomeFile` ed anche ad aggiungere `?NomeFile=` all'URL, ma continua a rinominarlo.

**Comment by andreapoli** [comment]
> il nome del file nella richiesta HTTP, e abbiamo notato che GovWay lo rinomina, incrementando correttamente il progressivo, ma non troviamo questa funzione nella documentazione.

Rientra nella gestione interna del protocollo SDICoop effettuata da GovWay. Non è una funzionalità visibile all'utente il quale utilizza GovWay per inviare la fattura senza "preoccuparsi" del protocollo SDICoop e per questo motivo non ne trovi documentazione.

> Come possiamo fare a forzare il nome del file che vogliamo trasmettere?

Non è una funzionalità attualmente presente. 

> Ho provato ad includere nella richiesta HTTP POST, con la quale invio il file, gli header `Content-Disposition` e `GovWay-SDI-NomeFile` ed anche ad aggiungere `?NomeFile=` all'URL, ma continua a rinominarlo.

Se venisse aggiunta banalmente la possibilità di utilizzare il nome fornito via header (o url parameter), si potrebbero poi verificare la generazione di nomi duplicati quando tale header non fosse presente e GovWay avrebbe quindi il compito di generare il progressivo. 
La funzionalità richiede quindi una implementazione più complessa per evitare i duplicati e per questo motivo non è in programma attualmente tra le funzionalità che saranno presenti nella nuova versione

**Comment by marcomarsala** [comment]
Noi dovremmo iniziare a inviare tramite GovWay, con un canale accreditato sul quale abbiamo già effettuato degli invio, quindi il nostro progressivo non partirebbe da uno (diversamente i file sarebbero scartati da SDI per nome file duplicati), la progressività nel nome del file è già gestita dalla nostra applicazione che genera le fatture e che attualmente invia tramite un’altra libreria che stiamo abbandonando. Esiste qualche soluzione?

**Comment by andreapoli** [comment]
> O, in alternativa, è possibile forzare almeno il numero progressivo di partenza agendo sul DB

Con la select riportata di seguito puoi individuare i progressivi attivi.
Esiste un progressivo associato ad ogni trasmittente (colonna 'info_associata'). 

Come indicato dalla [specifica tecnica dello sdi](https://www.fatturapa.gov.it/export/fatturazione/sdi/Specifiche_tecniche_SdI_v1.6.pdf) al paragrafo 2.2
Il progressivo univoco del file è rappresentato da una stringa alfanumerica di
lunghezza massima di 5 caratteri e con valori ammessi [a-z], [A-Z], [0-9].

select * from id_messaggio_relativo_prg ;
 progressivo | protocollo |   info_associata    |     ora_registrazione      
-------------+------------+---------------------+----------------------------
 0000C       | sdi        | IT01234567890       | 2018-07-20 13:30:41.915058

**Comment by marcomarsala** [comment]
Grazie, allora posso forzarlo agendo sul DB. 

Considerando che le specifica SDI più recenti permettono nel nome del file una qualsiasi P.IVA, mentre fino a qualche mese fa le specifiche richiedevano di utilizzare quella associata al canale trasmissivo, di fatto chiunque può fare un DDoS a un altro canale inviando molte fatture per saturare i progressivi a disposizione (sperimentato).

La gestione dei file duplicati dovrebbe quindi poter essere responsabilità dell’applicazione che invia, perché è un caso che potrà comunque verificarsi.

**Comment by marcomarsala** [comment]
Volevo sapere se GovWay gestisce chiamate concorrenti, considerato che ogni chiamata deve effettuare un'operazione non atomica come leggere il progressivo ed incrementarlo.

**Comment by andreapoli** [comment]
> A prescindere da quanto sopra, volevo sapere se GovWay gestisce chiamate concorrenti,

Certamente.

> ogni chiamata deve effettuare un'operazione non atomica come leggere il progressivo ed incrementarlo

Il progressivo (lettura e incremento) viene generato da GovWay gestendo opportunamente la sincronizzazione in presenza di chiamate concorrenti. Non verranno mai generati due progressivi identici relativi ad uno stesso trasmittente.

**Comment by andreapoli** [comment]
> Come possiamo fare a forzare il nome del file che vogliamo trasmettere? Ho provato ad includere nella richiesta HTTP POST, con la quale invio il file, gli header `Content-Disposition` e `GovWay-SDI-NomeFile` ed anche ad aggiungere `?NomeFile=` all'URL, ma continua a rinominarlo.

Nella nuova versione è possibile disabilitare la generazione, da parte di GovWay, dei nomi SDI da associare alle fatture da inviare (fatturazione attiva) o alle notifiche esito (fatturazione passiva) agendo sulle proprietà 'org.openspcoop2.protocol.sdi.fatturazione[Attiva/Passiva].nomeFile.gestione' nel file '/etc/govway/sdi_local.properties'.

Se viene disabilitata la gestione (attiva per default), la gestione dei nomi dei file (correttezza sintattica, univocità, ...) è demandata all'Applicativo Client che deve obbligatoriamente fornire il nome del file attraverso uno dei seguenti modi:
- query parameter 'NomeFile'
- header http 'SDI-NomeFile' 
- header http 'GovWay-SDI-NomeFile'
