### ISSUE TITLE
GovWay non scrive log

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#32]
Buongiorno,

riscontro il seguente errore durante l'invio di una fattura:

```
<problem xmlns="urn:ietf:rfc:7807"><type>https://httpstatuses.com/500</type><tit
le>Internal Server Error</title><status>500</status><detail>Sistema non disponib
ile</detail><govway_status>integration:GOVWAY-500</govway_status></problem>
```

GovWay non scrive nessun log nella cartella configurata in fase di installazione (è scrivibile dall'utente sotto il quale gira l'Application Server). Nel log dell'Application Server non vengono scritti errori al momento dell'invio.

Il sistema è Ubuntu 16, GovWay 3.0.1 (ha funzionato su questa macchina fino a venerdì), versione di Java:
```
openjdk version "1.8.0_191-ojdkbuild"
OpenJDK Runtime Environment (build 1.8.0_191-ojdkbuild-12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by andreapoli** [comment]
Verifica che GovWay sia stato inizializzato correttamente all'avvio dell'Application Server.
Si deve analizzare a riguardo il log dell'Application Server; allegalo eventualmente all'Issue.

**Comment by marcomarsala** [comment]
Allego un log pulito. Ho stoppato l'Application Server, troncato il log e avviato nuovamente l'AP.
[log.zip](https://github.com/link-it/govway/files/3057334/log.zip)

**Comment by marcomarsala** [comment]
A seguito di riavvio funziona correttamente. Nel file server.log dell'avvio precedente risultava un errore di I/O durante la scrittura del file di log, dovuto a mancanza di permessi sul filesystem, ma dopo averli corretti si è reso comunque necessario riavviare l'AP. Ora i log vengono scritti e l'errore 500 non è più presente.
