### ISSUE TITLE
Esporre WSDL delle erogazioni

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#33]
Buongiorno,

il WSDL usato dalle erogazioni è accessibile dall'esterno? Potrebbe essere utile per effettuare dei test con i vari client SOAP web, che richiedono tutti un URL del WSDL anziché permetterne l'upload (attualmente uso SoapUI o Boomerang in locale).

**Comment by andreapoli** [comment]
E' una funzionalità che verrà aggiunta nelle prossime versioni.

**Comment by andreapoli** [comment]
Con la versione attuale per creare i progetti di test nei programmi da te citati puoi utilizzare l'upload di un wsdl disponibile in locale, supportato da entrambi i programmi. Dopo aver creato i progetti, puoi modificare la url utilizzata per spedire la richiesta indicando la url di invocazione esposta da GovWay.

Ad esempio nel caso di Boomerang per creare un progetto basato sul servizio [LuhnChecker](https://ws.cdyne.com/creditcardverify/luhnchecker.asmx) puoi scaricare in locale il [wsdl](https://ws.cdyne.com/creditcardverify/luhnchecker.asmx?wsdl).
Dopodichè devi creare un nuovo servizio su Boomerang facendo il browsing del [wsdl](https://ws.cdyne.com/creditcardverify/luhnchecker.asmx?wsdl) scaricato (disponibile ad es. in /tmp/luhnchecker.wsdl).
![TEST](https://user-images.githubusercontent.com/16049098/55780742-f8ff5780-5aa8-11e9-981e-7191cbaad098.png)

Su Boomerang oltre a caricare il wsdl devi indicare anche il corretto ServiceName.
Una volta creato il servizio, puoi creare la richiesta per il servizio SOAP dove è possibile indicare la url di invocazione di GovWay.
![TEST2ù](https://user-images.githubusercontent.com/16049098/55780972-6f03be80-5aa9-11e9-9467-ec5f7a004ac0.png)

**Comment by andreapoli** [comment]
L'interfaccia WSDL di una API SOAP, registrata su GovWay, è adesso ottenibile attraverso una invocazione HTTP GET utilizzando la medesima url di invocazione arricchita del prefisso '?wsdl'.
Nell'installazione di default la gestione delle richieste HTTP GET con prefisso '?wsdl' è disabilitata e tali richieste ottengono un errore 'HTTP 404 Not Found'.
Per abilitare la funzionalità è possibile agire sul file esterno '/etc/govway/govway_local.properties' abilitando le seguenti proprietà:
- 'org.openspcoop2.pdd.pd.generateWsdl': abilita la gestione sulle fruizioni
- 'org.openspcoop2.pdd.pa.generateWsdl': abilita la gestione sulle erogazioni
