### ISSUE TITLE
Accedere ai dati di monitoraggio dall'esterno

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#34]
Ho visto che nella console di monitoraggio è presente un semaforo rosso/verde che indica in modo preciso lo stato del gateway, è possibile accedere a questo dato dall'esterno, in modo automatizzato?

**Comment by marcomarsala** [comment]
Ho visto nei file di configurazione in /etc/govway che è presente questo URL: http://127.0.0.1:8080/govway/check che sembrerebbe indicare ciò che serve a me, ma non ho capito come si usa.

**Comment by andreapoli** [comment]
La url indicata è esattamente quella utilizzata dalla console di monitoraggio.

La puoi invocare tramite una http GET:

- se ottieni 200 significa che il Gateway è correttamente in funzione
- altrimenti viene ritornato 500, e nel payload http è presente il motivo dell'errore.
