### ISSUE TITLE
Testare ricezione fatture e notifiche con SoapUI

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#35]
Buongiorno,

sto effettuando dei test di ricezione fatture e notifiche tramite SoapUI, effettuando una chiamata all'endpoint come se fossi io il SDI. Per permettere questo ho prima disabilitato il controllo accessi in GovWay.

Sono riuscito a impostare quasi tutto correttamente, tuttavia i file fattura creati su disco sono vuoti. Nella console di monitoraggio trovo:

`errorProtocol | ConsegnaContenutiApplicativi | Riscontrato errore durante la consegna del messaggio applicativo con ID [9bc89f1f-9040-430b-8175-8a7ef99d40a6], generato dal mittente [sdi/CentroServiziFatturaPA] per il servizio applicativo [sdi_APP/sdi_RicezioneFatture/v1], e tentato di consegnare con connettore di tipo [file] (location: /data/ReceivedInvoices/IT01641790702_PROVA.xml [headers: /data/ReceivedInvoices/IT01641790702_PROVA.xml.properties]): Errore avvenuto durante la consegna su FileSystem: @@@ OpenSPCoop2DataContentHandler.getContent() error: OpenSPCoop2DataContentHandler Signature non presente (length is too small) (sourceException: Sbustamento msg_inputStream non riuscito: @@@ OpenSPCoop2DataContentHandler.getContent() error: OpenSPCoop2DataContentHandler Signature non presente (length is too small))`

E' normale? Forse GovWay controlla che i messaggi inviati da SDI siano firmati?

**Comment by andreapoli** [comment]
L'errore sembra dovuto ad un messaggio, prodotto tramite SoapUI, che non è conforme al protocollo SDICoop.
