### ISSUE TITLE
Ricezione file dei metadati

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#36]
Buongiorno,

ho notato che ricevendo fatture passive tramite GovWay, non viene salvato il file dei metadati. Vengono salvati solo il file fattura e il file .properties contenente gli header.

C’è modo di salvare anche il file dei metadati?

**Comment by andreapoli** [comment]
Le informazioni presenti nel file metadati vengono tutte veicolate tramite singoli header http all'applicativo di consegna. Nel tuo caso dovresti quindi riscontrarle nel file .properties.

La consegna del file metadati, nel formato originale ricevuto, non è stato ritenuto essenziale inoltrarlo all'applicativo non essendo un file firmato dallo SDI, e quindi lo scambio di tali informazioni tramite header http è equivalente.

**Comment by marcomarsala** [comment]
Grazie. Sarebbe utile poter decidere tramite un opzione il comportamento desiderato, soprattutto quando si deve integrare GovWay con applicazioni preesistenti che si aspettano i dati nel formato SDI.

**Comment by andreapoli** [comment]
L'unica possibilità per fornire il file metadati all'applicativo è quello di aggiungerlo come valore di un nuovo header di integrazione, codificandolo in base64.

Nel tuo caso quindi te lo troveresti come valore di una proprietà nel file .properties. Dovresti poi decodificarlo (base64 decode) e fornirlo all'applicazione interna nella forma di integrazione più opportuna.

**Comment by marcomarsala** [comment]
Ok, sarebbe opportuno poterlo ricevere già decodificato o, nel caso del connettore File, ottenerlo salvato su disco, esattamente come avviene per le fatture (magari aggiungendo un terzo campo alla configurazione del connettore).

**Comment by andreapoli** [comment]
> Ok, sarebbe opportuno poterlo ricevere già decodificato o, nel caso del connettore File, ottenerlo salvato su disco, esattamente come avviene per le fatture (magari aggiungendo un terzo campo alla configurazione del connettore).

Tutti i connettori di GovWay sono concepiti per poter serializzare il body e le informazioni di trasporto del messaggio presente nel contesto. Questo succede sia per i connettori standard http che per quelli avanzati come JMS (il body corrisponde al messaggio JMS mentre gli header sono proprietà del messaggio) e File (il body e tutti gli header vengono serializzati in due file differenti). Inoltre tutti i connettori sono utilizzabili in qualsiasi profilo di utilizzo del gateway (Fatturazione Elettronica, SPCoop, API Gateway). Ogni funzionalità aggiunta ad un connettore deve quindi poter essere utilizzata indipendentemente dal profilo.

**Comment by andreapoli** [comment]
Nella nuova versione è possibile configurare GovWay per consegnare all'applicativo, oltre alla fattura, anche il file Metadati ricevuto dallo SDI. 
Il contenuto di tale file viene inserito, codificato in base64, nell'header HTTP 'GovWay-SDI-FileMetadati'.

La funzionalità, disabilitata per default, è attivabile abilitando la proprietà 'org.openspcoop2.protocol.sdi.fatturazionePassiva.consegnaFileMetadati' all'interno del file /etc/govway/sdi_local.properties
