### ISSUE TITLE
Fuso orario errato nella legenda del grafico 'Distribuzione Esito messaggi'

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#37]
Ho modificato il fuso orario del sistema operativo Ubuntu in Europe/Rome, ma GovWay continua a 
mostrare il precedente fuso orario nella scheda Runtime. L'application server è WildFly.

E' necessario rieffettuare il deploy di GovWay o riavviare l'AP affinché legga il nuovo fuso orario del S.O.?

**Comment by FedericoLink** [comment]
Salve Marco,
dopo la modifica del timezone del sistema operativo è necessario un riavvio del WildFly.
Successivamente potrai vedere aggiornata la sezione  "Informazioni TimeZone" della scheda Runtime.

Federico

**Comment by marcomarsala** [comment]
La console di monitoraggio mostra comunque l’orario sbagliato di un’ora, nella legenda del grafico *Distribuzione Esito messaggi nell’ultimo periodo* se impostato su *Ultime 24 ore*

Il timezone risulta Europe/Rome (Central European Time), ora sono le 15:04 ma la console riporta:

_dal 02 maggio 2019, ore 16:06 al 03 maggio 201, ore 16:06_

**Comment by FedericoLink** [comment]
Salve Marco,
un'informazione per poter replicare il problema: il comando "date" sul server riporta l'orario corretto?
O risulta anche li corretto Timezone e orario disallineato?

Federico

**Comment by marcomarsala** [comment]
L’orario e il timezone sul server risultano entrambi corretti

________________________________
Da: Federico <notifications@github.com>
Inviato: Friday, May 3, 2019 7:35:00 PM
A: link-it/govway
Cc: Marco Marsala; Author
Oggetto: Re: [link-it/govway] Fuso orario errato nella legenda del grafico 'Distribuzione Esito messaggi' (#37)


Salve Marco,
un'informazione per poter replicare il problema: il comando "date" sul server riporta l'orario corretto?
O risulta anche li corretto Timezone e orario disallineato?

Federico
