### ISSUE TITLE
Paginazione Storico della console di monitoraggio

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#38]
Ho notato che la paginazione della funzionalità Storico, nella console di monitoraggio, non mostra il numero totale di risultati e/o pagine trovati.

**Comment by andreapoli** [comment]
Il totale dei risultati (e il numero di pagine), nello storico della transazioni, non viene fornita per motivi di performance. Nelle base dati che possiedono un numero elevato di record, ottenere tali informazioni è costoso.

Se vuoi provare ad abilitare la funzionalità puoi aggiungere la seguente proprietà al file '/etc/govway/monitor_local.properties':
- transazioni.storico.utilizzaCount.enabled=true

Dopo aver aggiunto la proprietà è richiesto un riavvio dell'Application Server o il redeploy della console 'govwayMonitor'.
