### ISSUE TITLE
Scala grafico Distribuzione Esito messaggi in console di monitoraggio

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#39]
Ho notato che la scala e le etichette sulla dimensione “Numero Esito” del grafico in oggetto rimane errata per alcuni minuti, nelle visualizzazioni diverse da Ultimo anno, in presenza di invii massivi.

È invece corretta nella funzione Analisi Statistica.

Ho effettuato un invio massivo di fatture in pochi minuti, la visualizzazione Ultime 24 ore, mostrava appena una manciata di esiti (7), mentre la visualizzazione Ultimo anno era da subito corretta (35000). Anche effettuando logout e login e svuotando la cache del browser il problema non si risolveva.

Dopo alcuni minuti, il grafico è tornato corretto. I grafici vengono ricalcolati in background?

Ho notato anche un’altra anomalia: a seguito dell’invio massivo, andato a buon fine, il semaforo indica gateway non funzionante per Connection Refused, ma in realtà è tutto perfettamente operativo.

**Comment by andreapoli** [comment]
> Dopo alcuni minuti, il grafico è tornato corretto. I grafici vengono ricalcolati in background?

I risultati statistici vengono ricalcolati ogni ora per qualsiasi 'Unità di tempo' tu scelga (orario, giornaliero, settimanale, mensile). Questo significa che l'informazione sulle transazioni gestite dal gateway relativa all'ultimo intervallo (ora corrente, giorno corrente, ....) viene aggiornata ogni ora (o al riavvio dell'application server).

E' previsto per la prossima versione di utilizzare un intervallo di aggiornamento, per l'unità di tempo 'oraria', più frequente (ogni 5 minuti).

**Comment by andreapoli** [comment]
> Ho notato anche un’altra anomalia: a seguito dell’invio massivo, andato a buon fine, il semaforo indica gateway non funzionante per Connection Refused, ma in realtà è tutto perfettamente operativo.

La console di monitoraggio per verificare lo stato di funzionamento del Gateway invoca il servizio di check alla url indicata nel file '/etc/govway/monitor_local.properties':
- http://127.0.0.1:8080/govway/check

Durante l'invio massivo hai saturato le connessioni http e quindi la console non riusciva ad invocare il servizio (connection refused...).
Per evitare questa condizione puoi creare un nuovo connettore http sull'application server, in ascolto su una porta differente, dedicata al monitoraggio. Se procedi con questa soluzione devi riconfigurare i puntamenti presenti nei file '/etc/govway/monitor_local.properties' e '/etc/govway/console_local.properties' e devi riavviare l'application server.
