### ISSUE TITLE
Manipolazione richiesta SOAP

### ISSUE THREAD

**Issue by apetrelli** [link-it/govway#40]
Buongiorno
stavo valutando GovWay per un progetto in fase di studio.
Volevo sapere se è possibile modificare, in qualche modo, le richieste SOAP prima che vengano inviate al web service finale. In particolare dovrei aggiungere degli header SOAP custom.
Tali web service esistono come progetti legacy ed è desiderabile evitare di modificarli, se possibile.
Ho installato GovWay in locale su Linux con DB PostgreSQL 11 e Wildfly 16.

Grazie
Antonio Petrelli 

P.S.: Ho mandato il quesito sulla mailing list ma non so quando questa sia attiva, visto che negli archivi vedo messaggi fino al 2017.

**Comment by andreapoli** [comment]
> Volevo sapere se è possibile modificare, in qualche modo, le richieste SOAP prima che vengano inviate al web service finale. In particolare dovrei aggiungere degli header SOAP custom.

Nella nuova versione appena rilasciata (v3.1.0.rc1) è possibile realizzare quello che tu chiedi grazie ad una delle nuove funzionalità introdotte: la **Trasformazione dei Messaggi**.

Nella [Guida alla Console di Gestione](https://github.com/link-it/govway/blob/master/resources/doc/pdf/GovWay-ManualeUtente.pdf) alla sezione '2.12.2 Trasformazione', tra i vari i dettagli su come attuare la configurazione, puoi vedere come si possa aggiungere facilmente header http custom.

La nuova release è disponibile [qua](https://github.com/link-it/govway/releases/download/3.1.0.rc1/govway-installer-3.1.0.rc1.tgz).

**Comment by apetrelli** [comment]
Perfetto grazie!
