### ISSUE TITLE
Trasformazioni SOAP: accesso a codice esterno e richiesta HTTP

### ISSUE THREAD

**Issue by apetrelli** [link-it/govway#41]
Salve
Vorrei sapere se nella trasformazione delle erogazioni tramite template (Velocity o Freemarker non fa differenza) è possibile accedere a un codice esterno a GovWay e alla richiesta HTTP.
Questo è il mio caso d'uso:
Nell'ambito di una chiamata SOAP, devo prendere il nome del principal dalla richiesta HTTP (nel senso di HttpServletRequest), quindi devo invocare una libreria esterna che si collega a un servizio custom di gestione informazione utenti, quindi devo usare l'oggetto ritornato per scrivere l'header SOAP.
È possibile effettuare un'operazione del genere con le trasformazioni di GovWay 3.1?

Grazie

**Comment by andreapoli** [comment]
È possibile realizzare quanto richiedi.
Ti allego un [archivio zip](https://github.com/link-it/govway/files/3236611/templates.zip) contenente due esempi di template 'Velocity' che realizzano lo scenario che hai descritto.

Il primo template (template1.vm) estrae il principal dal contesto della richiesta, lo utilizza per invocare un servizio http esterno ed utilizza la risposta come valore di un elemento di un header custom.

Il secondo template (template2.vm) utilizza una classe personalizzata all'interno della quale puoi inserire una logica di invocazione di un servizio custom complessa a piacere. Questa seconda soluzione richiede il caricamento degli archivi jar, che implementano le classi personalizzate, all'interno dell'archivio 'govway.ear/lib' e il restart dell'Application Server. 

Come puoi vedere dai templates allegati il principal viene acceduto dal contesto della richiesta. Questo richiede che sia configurata, nel Controllo degli Accessi dell'API, un'autenticazione di tipo 'principal'. Per maggiori dettagli a riguardo puoi consultare la [Guida alla Console di Gestione](https://github.com/link-it/govway/blob/master/resources/doc/pdf/GovWay-ManualeUtente.pdf) nella sezione '2.7.2 Autenticazione'.

**Comment by apetrelli** [comment]
Grazie mille, davvero esaustivo! Scusa se ho fatto questa domanda ma dalla documentazione non trovavo nulla. A tal proposito forse sarebbe il caso di aggiungere questi esempi nel PDF, oppure creare qualche progetto di esempio.
