### ISSUE TITLE
Controllo Accessi - Autorizzazione per Token Claims con regular expressions

### ISSUE THREAD

**Issue by bpnx** [link-it/govway#44]
Nella sezione di "Autorizzazione per Token Claims", in "Controllo accessi", sarebbe 
molto utile se esistesse la possibilità di effettuare match basati su regular expression:
oltre alla comodità dell'utilizzo delle regexp, si aprirebbe la possibilità di effettuare la verifica
che un determinato claim sia semplicemente presente con un valore non nullo

**Comment by andreapoli** [comment]
### Situazione attuale
L'autorizzazione per token claims permette di effettuare dei semplici controlli sui valori dei claim presenti nel token, una volta verificato che il token sia valido. La funzionalità è utilizzabile nei contesti in cui il controllo di autorizzazione possiede una logica semplice che si basa sulla verifica del valore di uno o più claim. Dove serve una logica più complessa (ad es. con rami 'if-else' ) il controllo deve essere effettuato utilizzando una XACMLPolicy.

### Esigenza emersa
Sempre basandosi sul fatto di verificare il valore di un claim, è emersa la necessità di poter fornire un valore dinamico in funzione dei dati della richiesta. Ad esempio controlli tipici si basano sul match tra i valori presenti nel token e quelli portati nella richiesta (url, header, messaggio) partendo dal presupposto che l'identificativo utilizzato nella richiesta coincida (o sia ricavabile attraverso la concatenazione di stringhe) con il valore presente nel token claim.
In altri contesti è sufficiente verificare che un claim sia presente e valorizzato, indipendentemente dal valore.
Tutte questi controlli, possono essere attuati allo stato attuale su GovWay definendo una XACMLPolicy. Ad esempio per verificare che il valore del claim 'sub' presente nel token sia identico a quello fornito nel query parameter 'sub' è possibile utilizzare la seguente [policy](https://github.com/link-it/govway/files/3396843/esempioPolicy.txt).

### Nuova funzionalità
Si vuole estendere i controlli attuabili nella sezione 'Autorizzazione per Token Claims' all'interno del Controllo degli Accessi per soddisfare le esigenze descritte senza dover ricorrere alla definizione di XACMLPoliy. Nella nuova funzionalità sarà inclusa anche la possibilità di indicare una espressione regolare per verificare il valore di un claim e la possibilità di verificare che un claim sia semplicemente presente con un valore non nullo come richiesto da @bpnx in questo Issue #44.

I valori utilizzabili per il controllo di ogni claim all'interno della sezione 'Autorizzazione per Token Claims'  saranno i seguenti:
- valoreSingolo o lista di valori attesi separati da ','. I valori indicati possono contenere i placeholder utilizzabili attualmente nelle [trasformazioni](https://govway.org/documentazione/console/profiloApiGateway/trasformazioni/valoriDinamici.html).
- ${anyValue} : indica qualsiasi valore non nullo.
- ${regExpMatch:EXPR}: la regola è soddisfatta se l'intero valore del claim ha un match rispetto all'espressione regolare EXPR indicata.
- ${regExpFind:EXPR}: simile alla precedente regola, il match dell'espressione regolare può avvenire anche su una sottostringa del valore del claim.

Di seguito alcuni esempi:
- client_id=3 : viene verificato che il claim 'client_id' possieda il valore 3
- client_id=3,5,6 : viene verificato che il claim 'client_id' possieda il valore 3 o 5 o 6
- client_id=${anyValue} : viene verificato che il claim 'client_id' possieda un valore (not null e not empty)
- client_id=${regExpMatch:[0-9]} : viene verificato che il claim 'client_id' possieda esattamente una cifra decimale attraverso la verifica di un match con l'espressione regolare '[0-9]'
- client_id=${regExpFind:[0-9]} : viene verificato che il claim 'client_id' contenga una cifra decimale attraverso l'espressione regolare '[0-9]'
- client_id=${header:X-Prova} : viene verificato che il claim 'client_id' possieda lo stesso valore presente nell'header http 'X-Prova' presente nella richiesta
- client_id=cl_${header:X-Prova} : viene verificato che il claim 'client_id' possieda il valore presente nell'header http 'X-Prova'  arricchito del prefisso 'cl_'
- client_id=${query:prova} : viene verificato che il claim 'client_id' possieda lo stesso valore presente nel parametro 'prova' della url di invocazione
- client_id=${urlRegExp:EXPR} : viene verificato che il claim 'client_id' possieda lo stesso valore estratto dalla url di invocazione attraverso l'applicazione dell'espressione regolare EXPR
- client_id=${xPath:EXPR} : viene verificato che il claim 'client_id' possieda lo stesso valore estratto dalla richiesta xml tramite l'espressione XPath EXPR.
- client_id=${jsonPath:EXPR} : viene verificato che il claim 'client_id' possieda lo stesso valore estratto dalla richiesta json tramite l'espressione jsonPath EXPR.
