### ISSUE TITLE
Ripulire tabelle database

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#46]
Buongiorno,

quali tabelle del database possono essere periodicamente ripulite senza causare problemi a GovWay in esecuzione? Il nostro database ha raggiunto la dimensione di 28GB in soli tre mesi, di seguito le tabelle ordinate per dimensione.

 schemaname |          relname          | n_live_tup
------------+---------------------------+------------
 public     | msgdiagnostici            |   24293532
 public     | tracce_ext_protocol_info  |   17493242
 public     | tracce                    |    5136070
 public     | tracce_trasmissioni       |    4273786
 public     | transazioni               |    2999136
 public     | tracce_eccezioni          |    2605501
 public     | tracce_allegati           |     833028
 public     | statistiche_orarie        |      16617
 public     | statistiche_giornaliere   |       1045
 public     | statistiche_settimanali   |        217
 public     | audit_operations          |        155
 public     | statistiche_mensili       |         80
 public     | generic_property          |         45
 public     | notifiche_eventi          |         41
 public     | connettori_custom         |         37
 public     | connettori                |         17
 public     | operation_messages        |         13
 public     | port_type_azioni          |         10
 public     | audit_appender_prop       |          7
 public     | ct_config_policy          |          6
 public     | op2_semaphore             |          5
 public     | porte_applicative         |          4
 public     | statistiche               |          4
 public     | documenti                 |          4
 public     | mapping_erogazione_pa     |          4
 public     | servizi_applicativi       |          4
 public     | servizi                   |          4
 public     | porte_applicative_sa      |          4
 public     | accordi                   |          4
 public     | id_messaggio_relativo_prg |          4
 public     | port_type                 |          4
 public     | pa_correlazione           |          3
 public     | soggetti                  |          3
 public     | audit_appender            |          2
 public     | porte_delegate_sa         |          2
 public     | porte_delegate            |          2
 public     | mapping_fruizione_pd      |          2
 public     | config_protocolli         |          2
 public     | servizi_fruitori          |          2
 public     | users                     |          2
 public     | users_stati               |          2
 public     | pd_mtom_request           |          2
 public     | pa_azioni                 |          2
 public     | ct_config                 |          1
 public     | credenziale_mittente      |          1
 public     | generic_properties        |          1
 public     | audit_conf                |          1
 public     | pd_correlazione           |          1
 public     | pdd                       |          1
 public     | db_info                   |          1
 public     | routing                   |          1
 public     | registri                  |          1
 public     | configurazione            |          1
 public     | pa_soggetti               |          1
 public     | pd_correlazione_risposta  |          1
 public     | db_info_console           |          1
 public     | asincrono                 |          0
 public     | pa_ruoli                  |          0
 public     | dump_appender_prop        |          0
 public     | pd_mtom_response          |          0
 public     | dump_config               |          0
 public     | configurazione_stati      |          0
 public     | stat_settimane_contenuti  |          0
 public     | lista_ext_protocol_info   |          0
 public     | parameters                |          0
 public     | pa_properties             |          0
 public     | scope                     |          0
 public     | servizi_fruitori_azione   |          0
 public     | ct_active_policy          |          0
 public     | pa_security_request       |          0
 public     | users_soggetti            |          0
 public     | id_messaggio              |          0
 public     | sa_ruoli                  |          0
 public     | servizi_pdd               |          0
 public     | stat_giorni_contenuti     |          0
 public     | plugins_conf_filtri       |          0
 public     | sequenza_da_inviare       |          0
 public     | msgdiag_appender_prop     |          0
 public     | accordi_coop_partecipanti |          0
 public     | tracce_appender           |          0
 public     | ruoli                     |          0
 public     | acc_serv_componenti       |          0
 public     | msgdiag_ds_prop           |          0
 public     | messaggi                  |          0
 public     | transazioni_info          |          0
 public     | plugins_azioni_comp       |          0
 public     | msgdiag_ds                |          0
 public     | pd_azioni                 |          0
 public     | dump_allegati             |          0
 public     | accordi_cooperazione      |          0
 public     | msg_servizi_applicativi   |          0
 public     | tracce_riscontri          |          0
 public     | ricerche_personalizzate   |          0
 public     | pa_mtom_request           |          0
 public     | porte_applicative_sa_auth |          0
 public     | dump_config_regola        |          0
 public     | audit_filters             |          0
 public     | correlazione_applicativa  |          0
 public     | api_resources_response    |          0
 public     | pa_scope                  |          0
 public     | plugin_info               |          0
 public     | riscontri_da_ricevere     |          0
 public     | config_tran_plugins       |          0
 public     | servizi_fruitori_azioni   |          0
 public     | pd_security_request       |          0
 public     | stat_orarie_contenuti     |          0
 public     | dump_contenuti            |          0
 public     | servizi_pdd_filtri        |          0
 public     | pd_ruoli                  |          0
 public     | accordi_azioni            |          0
 public     | api_resources_media       |          0
 public     | config_transazioni        |          0
 public     | gestione_errore           |          0
 public     | tracce_ds_prop            |          0
 public     | plugins_conf_servizi      |          0
 public     | servizi_azione            |          0
 public     | plugins_servizi_comp      |          0
 public     | soggetti_ruoli            |          0
 public     | pa_correlazione_risposta  |          0
 public     | id_messaggio_prg          |          0
 public     | definizione_messaggi      |          0
 public     | conf_risorse_contenuti    |          0
 public     | stat_personalizzate       |          0
 public     | tracce_appender_prop      |          0
 public     | gestione_errore_soap      |          0
 public     | plugins                   |          0
 public     | audit_binaries            |          0
 public     | gestione_errore_trasporto |          0
 public     | tracce_ds                 |          0
 public     | users_servizi             |          0
 public     | lista_eccezioni           |          0
 public     | plugins_conf_azioni       |          0
 public     | transazioni_export        |          0
 public     | acc_serv_composti         |          0
 public     | pd_properties             |          0
 public     | dump_multipart_header     |          0
 public     | connettori_properties     |          0
 public     | protocol_properties       |          0
 public     | dump_header_trasporto     |          0
 public     | stat_mensili_contenuti    |          0
 public     | lista_riscontri           |          0
 public     | pa_mtom_response          |          0
 public     | dump_header_allegato      |          0
 public     | dump_messaggi             |          0
 public     | pa_security_response      |          0
 public     | repository_buste          |          0
 public     | lista_trasmissioni        |          0
 public     | pd_security_response      |          0
 public     | id_messaggio_relativo     |          0
 public     | api_resources_parameter   |          0
 public     | pd_scope                  |          0
 public     | api_resources             |          0
 public     | plugins_filtro_comp       |          0
 public     | pdd_sys_props             |          0
 public     | dump_appender             |          0
 public     | sequenza_da_ricevere      |          0
 public     | msgdiag_appender          |          0
 public     | operations                |          0
 public     | servizi_azioni            |          0
(159 rows)

**Comment by andreapoli** [comment]
Le tabelle sono suddivisibili in "classi" funzionali differenti: tracce, dump, statistiche, audit e tutte le altre. Tutte le tabelle appartenenti alle 4 classi sopra indicate contengono tabelle i cui record aumentano giorno dopo giorno in base al numero di transazioni che transitano sul gateway (tracce, dump, statistiche)  o in base al numero di operazioni effettuate sulle console di gestione (classe audit). Le restanti tabelle invece contengono le configurazioni gestite tramite la console di gestione.

Per poter effettuare uno svecchiamento periodico dei record, ogni tabella, appartenente ad una delle 4 classi sopra indicate, possiede una colonna di tipo 'TIMESTAMP' . Di seguito ti riporto le tabelle che appartengono ad ogni classe di dato, indicandoti tra parentesi la colonna che ti permette di effettuare il filtro temporale. 

- classe 'tracce': msgdiagnostici (gdo), tracce_eccezioni (gdo), tracce_riscontri (gdo), tracce_trasmissioni (gdo), tracce_allegati (gdo), tracce_ext_protocol_info (gdo), tracce (gdo), transazioni (data_ingresso_richiesta), notifiche_eventi (ora_registrazione)
- classe 'dump' (salvataggio dei messaggi): dump_header_allegato (dump_timestamp), dump_allegati (dump_timestamp), dump_contenuti (dump_timestamp), dump_header_trasporto (dump_timestamp), dump_multipart_header (dump_timestamp), dump_messaggi (dump_timestamp)
- classe 'statistiche' (informazioni statistiche): statistiche_orarie (data), statistiche_giornaliere (data), statistiche_settimanali (data), statistiche_mensili (data)
- classe 'audit': audit_binaries (time_rec), audit_operations (time_request)

**Comment by andreapoli** [comment]
> * classe 'tracce'

Aggiungo in questa classe anche la tabella credenziale_mittente (ora_registrazione)
