### ISSUE TITLE
Limitare accesso a console

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#47]
Buongiorno,

sto cercando di limitare l'accesso a govwayConsole ai soli utenti che si collegano tramite una VPN. Attualmente la console risponde sullo stesso IP e porta degli endpoint di erogazioni e fruizioni, che devono ovviamente rimanere esposti sul web.

E' possibile configurare la console affinché risponda su IP o porta differenti?

**Comment by FedericoLink** [comment]
Salve Marco,
generalmente per consentire di personalizzare gli accessi a GovWay non esponiamo direttamente le Console di configurazione/monitoraggio o gli endpoint di fruizione ed erogazione. Gli accessi vengono mediati da un front-end (tipicamente Apache) che grazie alla sua flessibilità consente di impostare una vasta gamma di ACL.
