### ISSUE TITLE
Trasformazione dell'URL dell'API

### ISSUE THREAD

**Issue by bpnx** [link-it/govway#48]
Buongiorno, vorrei creare un'erogazione su Govway tramite la quale poter chiamare nel 
backend un'API, utilizzando un parametro ricavato dall'access token del client

Ad esempio: in una erogazione ho definito l'API
GET /users
A fronte della richiesta da parte di un client, vorrei che govway prelevasse il sub dall'access
token (ipotizziame sub="123-456-789") del client e chiamasse quindi l'API nel backend in questo
modo:
GET /users/123-456-879
Ho visto che nei valori dinamici esiste "${tokenInfo:sub}", ma nelle trasformazioni mi pare di poter intervenire solo nel contenuto della request o della response ma non nella chiamata dell'API

E' possibile avere un esempio di configurazione di questo tipo ? O un'indicazione su come procedere ?

Grazie
Marco

**Comment by andreapoli** [comment]
Ciao Marco,

con l'attuale versione puoi implementare quanto richiesto tramite il seguente [template.ftl](https://github.com/link-it/govway/files/3626728/template.ftl.txt) FreeMarker abilitando la trasformazione del contenuto della richiesta. Se esamini il template, non viene creato alcun contenuto (la richiesta http GET rimane vuota) ma viene modificato il contesto fornito dal client arricchito del subject presente nel token come da te richiesto.
![workaround](https://user-images.githubusercontent.com/16049098/65154728-4dc9d580-da2c-11e9-9d77-8f3ca5d1f11e.png)

**Comment by andreapoli** [comment]
Per una API di tipo REST, come nello scenario da te evidenziato, sarebbe utile poter modificare il contesto fornito dal client direttamente nella maschera di configurazione della trasformazione della richiesta. Basterebbe aggiungere un campo editabile all'interno della sotto-sezione 'Trasporto' che permetta di definire trale trasformazione.
Nelle prossime versioni introdurremo tale funzionalità:
![Contesto](https://user-images.githubusercontent.com/16049098/65154219-62f23480-da2b-11e9-9702-b03930204ba8.png)

**Comment by bpnx** [comment]
Grazie Andrea, il tuo esempio funziona perfettamente, è esattamente ciò che cercavo
Marco
