### ISSUE TITLE
Errore 502 Bad Gateway

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#49]
Tentando di inviare una fattura specifica, ricevo l'errore 502 Bad Gateway, che non trovo in documentazione.

**Comment by andreapoli** [comment]
GovWay non genera errori con codice http '502'.

Per capire se l'errore è stato generato da un componente dispiegato architetturalmente prima di govway (es. un frontend web) o se effettivamente la richiesta è transitata su govway puoi verificare se nella risposta http è presente l'header http 'GovWay-Transaction-ID'.

Se presente, puoi utilizzarlo per effettuare una ricerca basata sull'id di transazione tramite la console 'govwayMonitor' ed ottenere maggiori dettagli sull'errore consultando i diagnostici.

Se invece non è presente deve essere effettuata un'analisi nei log degli apparati dispiegati davanti a GovWay.

**Comment by marcomarsala** [comment]
L'errore proviene da WildFly. Nella nostra configurazione c'è Apache di front-end che fa reverse proxy su WildFly.

In GovWay, però, abbiamo trovato un errore "Broken pipe":

![image](https://user-images.githubusercontent.com/5349718/66105021-98198d80-e5ba-11e9-9a29-8504145bb6f3.png)

**Comment by andreapoli** [comment]
L'errore "Broker Pipe" indica che la connessione client su cui GovWay dovrebbe inoltrare la risposta ricevuta dallo SDI non è più disponibile.

Esaminando le tempistiche dei diagnostici si vede che tra l'invio della fattura e la risposta dello SDI passa più di 1 minuto e mezzo. Hai quindi un timeout inferiore impostato o sull'Apache di frontend o direttamente sul client che chiude la connessione prima di poter ricevere la risposta.
