### ISSUE TITLE
Claims su header http

### ISSUE THREAD

**Issue by bpnx** [link-it/govway#50]
Buongiorno, ho trovato molto utile la possibilità di inoltrare al backend alcune informazioni contenute nel token sotto forma di "Govway headers". A quanto pare pero' la funzionalità è limitata ad alcuni claim (email, nome, cognome, ecc.ecc.): è possibile inoltrare il contenuto di altri claim, sempre sotto forma di http headers ?
Grazie
Marco

**Comment by andreapoli** [comment]
Ciao Marco,
    GovWay consente di realizzare quanto richiedi tramite la funzionalità di [trasformazione](https://govway.org/documentazione/console/profiloApiGateway/trasformazioni/index.html).

Devi attivare una trasformazione sulla tua API registrando per la richiesta un [nuovo header http](https://govway.org/documentazione/console/profiloApiGateway/trasformazioni/trasformazioneRichiesta.html) da inoltrare al backend. Per il nuovo header puoi utilizzare un [valore dinamico](https://govway.org/documentazione/console/profiloApiGateway/trasformazioni/valoriDinamici.html#valoridinamici) al fine di accedere al contesto della richiesta, e nel tuo caso particolare ai claims del token che govway ha validato.

Ad esempio puoi generare un header 'X-CustomToken-Aud' contenente il valore del claim 'aud' utilizzando come valore del nuovo header: 
- ${tokenInfo:claims[aud]}

![ADD](https://user-images.githubusercontent.com/16049098/67003291-ead86680-f0dd-11e9-9456-faa8f6e3b131.png)

**Comment by bpnx** [comment]
Ciao Andrea, grazie!
