### ISSUE TITLE
Aggiornamenti API in produzione

### ISSUE THREAD

**Issue by bpnx** [link-it/govway#52]
Ciao, ci stiamo chiedendo quale sia il modo di procedere consigliato, con Govway, per aggiornare API ed erogazioni, in produzione, per minimizzare il disservizio e per poter tornare indietro molto rapidamente nel caso in cui venga riscontrato qualche imprevisto.

Inoltre: aggiornare le definizioni API (utilizzate da una erogazione in produzione,molto utilizzata) con altre compatibili al 100% (ad esempio in caso di semplice aggiunta di una chiamata)  è rischioso o viene gestito da Govway senza problemi per gli utilizzatori ?

Grazie
Marco

**Comment by andreapoli** [comment]
> Ciao, ci stiamo chiedendo quale sia il modo di procedere consigliato, con Govway, per aggiornare API ed erogazioni, in produzione, per minimizzare il disservizio e per poter tornare indietro molto rapidamente nel caso in cui venga riscontrato qualche imprevisto.

Come descritto nell'Issue #54 puoi utilizzare il versionamento delle API per realizzare quanto chiedi.

Per tornare indietro è sufficiente:
- Ripristinare la precedente versione dell'API implementata nell'erogazione
- Ripristinare l'indirizzamento nel connettore dell'erogazione verso la precedente implementazione
- Effettuare il reset delle cache per rendere immediato il ripristino della vecchia configurazione.
