### ISSUE TITLE
Modifica API su erogazione

### ISSUE THREAD

**Issue by bpnx** [link-it/govway#54]
**Necessità:**
Quando si crea una nuova versione di API risulta comodo creare una nuova definizione completa. Sarebbe utile poter associare un'erogazione esistente alla nuova definizione API

**Soluzione:**
Permettere la modifica dell'erogazione nel parametro API 

**Alternative:**
Permettere la modifica dell'URL dell'erogazione

**Note:**
Sarebbe utile che questa modifica potesse essere fatta in produzione senza causare blocchi o problemi agli utenti (fermo restando ovviamente che le nuove API siano compatibili al 100% con quelle vecchie)

**Comment by andreapoli** [comment]
_> Permettere la modifica dell'erogazione nel parametro API_

Quanto richiesto è già presente su GovWay.
Per modificare l'erogazione, per quanto concere il parametro API, è necessario prima censire una nuova API con medesimo nome e versione differente.

Ad esempio supponiamo di aver registrato differenti versioni dell'API PetStore:
![APIv](https://user-images.githubusercontent.com/16049098/70324704-7c3b9d80-1830-11ea-88d5-bd82af8bccac.jpg)

Solamente se esiste più di una versione dell'API è possibile modificarne la versione implementata nell'erogazione tramite il bottone 'modifica':
![export (9)](https://user-images.githubusercontent.com/16049098/70326848-d2f7a600-1835-11ea-80a4-417d46211474.png)

Accedendo alla modifica dell'API è possibile modificare la versione implementata:
![SELECT_VERSION](https://user-images.githubusercontent.com/16049098/70325089-75f9f100-1831-11ea-9693-ec1df89ccb2a.png)

La modifica della versione dell'API implementata dall'erogazione, comporta automaticamente anche la modifica della versione dell'erogazione stessa. Questo si riflettte nell'url di invocazione che viene automaticamente aggiornata rispetto alla nuova versione.

**Comment by andreapoli** [comment]
_> Permettere la modifica dell'URL dell'erogazione_

Su GovWay vi è una gestione del versionamento effettuato su due componenti:
- API
- Erogazione o Fruizione dell'API

Come raccontato in precedenza, sulla singola erogazione/fruizione è possibile modificare la versione dell'API implementata solamente se ne esiste più di una versione. 
Questa modifica si riflette automaticamente anche sulla versione dell'erogazione/fruizione, e sulla url di invocazione, se la console di configurazione (pddConsole) viene utilizzata in [modalità standard](https://govway.org/documentazione/console/avanzate/modalita_avanzata.html) e non esiste già una  erogazione/fruizione con la nuova versione.

Utilizzando la console in [modalità avanzata](https://govway.org/documentazione/console/avanzate/modalita_avanzata.html) è anche possibile modificare puntualmente la versione dell'erogazione/fruizione e di conseguenza l'url di invocazione:
![export (8)](https://user-images.githubusercontent.com/16049098/70326876-ddb23b00-1835-11ea-8e24-db0fc872c0c5.png)

Come puoi vedere, accedendo alla modifica del nome dell'erogazione/fruizione con la console in modalità avanzata,  è possibile modificare la versione:
![VERSIONE_ERO](https://user-images.githubusercontent.com/16049098/70327426-14d51c00-1837-11ea-975f-5aab129ade06.png)

Effettuata la modifica avrai una erogazione con una versione indipendente dalla versione dell'API implementata. L'url di invocazione riflette la versione dell'erogazione:
![export (10)](https://user-images.githubusercontent.com/16049098/70327509-3b935280-1837-11ea-8902-d094ec543d4c.png)

**Comment by andreapoli** [comment]
> Sarebbe utile che questa modifica potesse essere fatta in produzione senza causare blocchi o problemi agli utenti (fermo restando ovviamente che le nuove API siano compatibili al 100% con quelle vecchie)

Dovresti riuscire a realizzare quanto chiedi:
- Registrando una nuova versione dell'API
- Associando la nuova versione all'erogazione già attiva in produzione
- Modificando il connettore dell'erogazione in modo da puntare la nuova implementazione dell'API.

Per rendere immediatamente operative le nuove configurazioni puoi effettuare il reset delle cache accedendo alla sezione 'Strumenti - Runtime - ResetAllCaches'

**Comment by bpnx** [comment]
Ciao Andrea, grazie; se posso suggerire una cosa, penso che sarebbe piu' immediato per l'amministratore, anziche' ricordarsi di creare un'api con lo stesso nome ma nuova versione 
una funzione associata ad un pulsante che permetta la creazione di una nuova versione di un'API esistente (anche solo che crei l'API con stesso nome e permetta di scegliere un nuovo numero di versione)
Grazie ancora
Marco

**Comment by andreapoli** [comment]
Ciao Marco, grazie per il suggerimento.

Nelle prossime versioni aggiungeremo il pulsante di creazione di una nuova versione all'interno del dettaglio dell'API. Di seguito un esempio di una possibile realizzazione della funzionalità richiesta:

![ADD_VERSIONE](https://user-images.githubusercontent.com/16049098/70341098-73f45a00-1852-11ea-91b1-a1a79f25412d.jpg)
