### ISSUE TITLE
import govway_pagopa_produzione-3.2.1 fallito

### ISSUE THREAD

**Issue by tizianatinnirello** [link-it/govway#55]
**Descrizione del Bug**
In fase di importazione di pagopa_produzione_3.2.1 (ma vale anche per il collaudo) viene generato questo errore all'ultimo step

Rilevato un errore durante l'import dell'archivio:
Accordo di Servizio Parte Comune [gw/WeSiDe:GenerazioneAvvisi:1] validazione fallita: Documento PagInf_RPT_RT_6_2_0.xsd (ruolo:null) non valido: Invalid byte 3 of 3-byte UTF-8 sequence.
problema identico sia con TOMCAT che con WildFly

**Come riprodurlo:**
E' sufficiente importare il file e seguire la procedura guidata

**Screenshots:**
Eventuali screenshot che mostrano l'errore.

**Ambiente:**
 - OS: [WINDOWS 10]
 - Browser: [Chrome o Firefox]
 - GovWay: [e.g. 3.2.1]
 - AS: [e.g WildFly 17]
 - DBMS: [MySQL]

**Comment by andreapoli** [comment]
Dall'errore che hai riportato sembra più un problema riconducibile al charset associato al database di GovWay.
Sulla nostra installazione, con MySQL v 5.7.27 e driver JDBC mysql-connector-java-5.1.40,  non siamo riusciti a replicare la problematica che hai segnalato.

Per poterti aiutare dovresti indicarci:
- versione del database
- versione del driver jdbc
- character_set_name e collation_name associato al database
- character_set_name e collation_name associato alle tabelle

Come puoi notare dagli script sql generati per MySQL dall'installer il character_set deve essere 'latin1' e il  collation_name deve essere 'latin1_general_cs'

Per ottenere il charset e il collation del database (es. dbname=govway) puoi utilizzare il comando:
   
    SELECT default_character_set_name, default_collation_name FROM information_schema.SCHEMATA WHERE schema_name = "govway";

Per ottenere il charset e il collation delle tabelle puoi utilizzare il comando:
  
    SELECT CCSA.character_set_name, CCSA.collation_name, T.table_name FROM information_schema.`TABLES` T,        information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA WHERE CCSA.collation_name = T.table_collation   AND T.table_schema = "govway";
