### ISSUE TITLE
Proposta di ottimizzazione procedura di aggiornamento database

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#58]
Buongiorno,

qual'è lo scopo delle seguenti istruzioni SQL per l'aggiornamento del database dalla versione 3.0.1 alla 3.1.0? 

`ALTER TABLE transazioni ADD COLUMN temp TEXT;
UPDATE transazioni SET temp=credenziali;
ALTER TABLE transazioni DROP COLUMN credenziali;
ALTER TABLE transazioni RENAME temp TO credenziali;`

L'UPDATE può richiedere ore su un database di produzione (su un database di 90GB abbiamo interrotto la query dopo 12 ore), e sembra che il risultato finale sia invariato. Sul medesimo DB una `ALTER TABLE transazioni ALTER COLUMN credenziali TYPE text;` richiede pochi secondi.

**Comment by marcomarsala** [comment]
Confermo che modificando lo script come indicato, l'aggiornamento va a buon fine in pochi minuti. Postgres 9.5.18.

**Comment by andreapoli** [comment]
Le patch SQL attualmente vengono generate nella stessa forma per tutti i tipi di database supportati e alcuni di questi (es. Oracle) non permettono la modifca del tipo da VARCHAR a CLOB, tramite il comando ALTER, quando esistono dei dati nella tabella oggetto della modifica. 
Ad es. usando il comando equivalente a quello da te proposto per oracle  'ALTER TABLE transazioni MODIFY credenziali CLOB;' si ottiene un errore 'ORA-22858: invalid alteration of datatype' e in questo caso è necessario seguire l'approccio di creazione di una nuova colonna per poi riversare i dati esistenti ed effettuare il renaming.

Quanto premesso la motivazione di avere una patch più efficente per i database che supportano la modifica, come ad es. postgresql, è evidente come anche da te riportato.

Nelle prossime versioni del prodotto le patch SQL verranno differenziate sui database supportati, per questi tipi di modifiche (VARCHAR -> TEXT/CLOB), preferendo sempre la versione più efficente supportata dal tipo di database.

**Comment by marcomarsala** [comment]
La vecchia versione 3.0.1 può funzionare con il database aggiornato? In altre parole, è possibile effettuare il downgrade dalla 3.2.2 alla 3.0.1?
