### ISSUE TITLE
Utilizzo DB eccessivo dopo aggiornamento da 3.0.1 a 3.2.2

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#60]
Dall'aggiornamento alla 3.2.2, riscontriamo un carico maggiore sul database (postgres 9.5.19, di circa 92 GB), che non si era mai verificato con la versione precedente 3.0.1 (live da quasi un anno). Allego un grafico dell'utilizzo di CPU. E' possibile che qualche nuova funzionalità, attiva di default nell'ultima versione, causi un carico maggiore? 

![image](https://user-images.githubusercontent.com/5349718/79055816-35333e00-7c50-11ea-8c28-a9bc98d16617.png)

**Comment by andreapoli** [comment]
> E' possibile che qualche nuova funzionalità, attiva di default nell'ultima versione, causi un carico maggiore?

Molto probabilmente è causato dalle nuove funzionalità descritte in #27 e dalla mancanza di un indice adeguato. Puoi provare a creare il seguente indice ?
  
  _CREATE INDEX tracce_ext_info_nv ON tracce_ext_protocol_info (name,value);_

Se dopo la creazione dell'indice non rilevi miglioramenti come workaround puoi disabilitare le nuove funzionalità agendo sul file di configurazione /etc/govway/sdi_local.properties:

 _org.openspcoop2.protocol.sdi.fatturazionePassiva.notifiche.enrichInfoFromFattura=false
 org.openspcoop2.protocol.sdi.fatturazioneAttiva.notifiche.enrichInfoFromFattura=false_

**Comment by marcomarsala** [comment]
Creando l'indice il problema si risolve, grazie.
![image](https://user-images.githubusercontent.com/5349718/79446679-e7fff500-7fde-11ea-858d-2824f991695c.png)
