### ISSUE TITLE
Errore durante fruizione SdIRiceviFile "unable to find valid certification path to requested target"

### ISSUE THREAD

**Issue by fcaspani01** [link-it/govway#61]
Buongiorno,
chiedo gentilmente supporto per la configurazione della govlet Fatturazione Attiva, in merito alla creazione del keystore .jks.
Ho seguito quanto descritto qui https://github.com/link-it/govway/issues/9 per creare il keystore ma purtroppo ricevo questo messaggio d'errore nella console di monitoraggio in seguito all'invio di una fattura verso https://testservizi.fatturapa.it/ricevi_file:

![Schermata 2020-05-13 alle 15 58 36](https://user-images.githubusercontent.com/57174797/81822172-0fd96e80-9533-11ea-8a62-70d08ae3cda7.png)

A cosa è dovuto? 
Sto sbagliando qualcosa in fase di generazione del keystore?
Di seguito i comandi da me lanciati per la generazione del jks:
```
# aggiungo password a chiave privata (sdi-xxxxx-client.key) utilizata per fare la richiesta di accreditamento
openssl rsa -aes256 -in sdi-xxxxx-client.key -out sdi-xxxxx-client-pwd.key

# converto il certificato client .cer fornito da fatturapa in .pem
openssl x509 -inform der -in SDI-xxxxx_client.cer -out SDI-xxxxx_client.pem

# creazione file pkcs12
openssl pkcs12 -export -inkey sdi-xxxxx-client-pwd.key -in SDI-xxxxx_client_client.pem -out fatturapa.p12 -name fatturapa_client

# creazione jks
keytool -importkeystore -srckeystore fatturapa.p12 -srcstoretype pkcs12 -destkeystore fatturapa.jks

# aggiungo CAEntratetest.cer e testservizi.fatturapa.it.cer al .jks
keytool -importcert -alias CAEntrate -file CAEntratetest.cer -keystore fatturapa.jks
keytool -importcert -alias testservizi.fatturapa.it -file testservizi.fatturapa.it.cer -keystore fatturapa.jks
```

**Comment by marklar79** [comment]
Hai utilizzato il file testservizi.fatturapa.it.cer che ti hanno consegnato insieme al Kit Di test?
Se si potresti verificare la validita' del certificato con questo comando:

openssl x509 -in testservizi.fatturapa.it.cer  -inform DER -noout -dates

**Comment by fcaspani01** [comment]
Lanciando il comando che mi hai suggerito risulta che il certificato che mi hanno fornito con il kit di test sia scaduto da mesi! :D  
![Schermata 2020-05-13 alle 23 02 56](https://user-images.githubusercontent.com/57174797/81865209-e4c04080-956d-11ea-8311-35135ca5b392.png)
Quindi l'errore che mi viene restituito da govway è dovuto a questo certificato scaduto?

**Comment by andreapoli** [comment]
L'errore è riconducibile al fatto che non è presente nel truststore il certificato ritornato dal server. La seguente [documentazione](https://govway.org/documentazione/installazione/finalizzazione/ssl/client.html) descrive come effettuare la configurazione SSL per le comunicazioni in uscita da GovWay.

Puoi verificare sia la connettività che il certificato ritornato dal server 'https://testservizi.fatturapa.it' direttamente sulla console di gestione (govwayConsole) utilizzando la funzionalità [verifica connettore](https://govway.org/documentazione/console/profiloApiGateway/connettore/verificaConnettivita.html#verificaconnettivitaconnettore). Tale funzionalità consente anche di effettuare il download del ceritifcato ritornato dal server che mi sembra sia diverso da quello fornito con il kit di test.

**Comment by fcaspani01** [comment]
Dopo aver ricreato il truststore con il certificato scaricato tramite govway sono riuscito a verificare la connettività del connettore e ad inviare una fattura verso testservizi.fatturapa.it.
Vi ringrazio per il supporto!

**Comment by andreapoli** [comment]
Ottimo.
Ti consiglio di creare anche l'indice indicato nell'issue #60 che ha permesso di risolvere la problematica descritta nell'issue stesso.
L'indicazione di creazione dell'indice rimane valida anche per l'ultima versione [3.3.0](https://github.com/link-it/govway/releases/tag/3.3.0).

**Comment by fcaspani01** [comment]
Ok grazie mille!
