### ISSUE TITLE
ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes

### ISSUE THREAD

**Issue by LeoLP1** [link-it/govway#66]
Buongiorno,

Stavo installando Govway 3.3.2 su una macchina linux con Tomcat 7.0.76.0 e MariaDB 10.2.23; quando ho lanciato l'importazione dell'sql "GovWay.sql" ho ricevuto l'errore "ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes".
Ho provato a cambiare il character e  ho provato anche a settare le seguenti variabili:
> SET GLOBAL innodb_large_prefix=ON;
> SET GLOBAL innodb_file_format=barracuda;
> SET GLOBAL innodb_file_per_table=true;

il risultato è sempre lo stesso. 
Sapresti darmi dei suggerimenti ?

**Comment by andreapoli** [comment]
Buongiorno @LeoLP1, si tratta di un bug presente nello script GovWay.sql generato per il tipo di database 'mysql'.

Come workaround per completare l'installazione puoi commentare il constraint:
`-- CONSTRAINT uniq_pa_behaviour_props_1 UNIQUE (id_porta,nome,valore),`

**Comment by LeoLP1** [comment]
@andreapoli Ti ringrazio per la risposta.
Suggerisci di effettuare la modifica che mi hai suggerito, o di passare magari a postgresql ?

**Comment by andreapoli** [comment]
Per noi PostgreSQL rappresenta il db di riferimento in fase di sviluppo, quindi è ovviamente un'ottima scelta.

**Comment by LeoLP1** [comment]
Confermo che la soluzione da te suggerita, permette di procedere con l'esecuzione dello script.
Ora valuteremo se continuare ad usare MySQL o passare a PostgreSQL.
Ti ringrazio.
