### ISSUE TITLE
Impossibile accedere alla console

### ISSUE THREAD

**Issue by LeoLP1** [link-it/govway#68]
Buongiorno,

ho installato su una macchina CentOS la versione di Govway 3.3.2 con

Tomcat 9
PostgreSQL 13
Java:
- openjdk 11.0.8 2020-07-14 LTS
- OpenJDK Runtime Environment 18.9 (build 11.0.8+10-LTS)
- OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode, sharing)

dopo aver seguito l'installazione, corretto gli eventuali errori che mi si presentavano nei log, ho provato a far l'accesso con le credenziali
```
amministratore: amministratore
password: Test1234
```
ma continuo a ricevere "Login o password errata!"

dove posso controllare l'errore da cosa sia causato?

**Comment by andreapoli** [comment]
Buongiorno @LeoLP1 , a quale console stai cercando di accedere, govwayConsole o govwayMonitor ? 

Verifica di utilizzare le credenziali corrette che hai impostato nell'installer, poichè queste credenziali verranno inserite codificate negli script SQL generati che hai usato per creare la base dati. Ogni console ha le proprie credenziali.

Se le credenziali sono corrette verifica eventuali errori presenti nei log generati dalle console govway_console*.log o goway_monitor*.log 
Ti suggerisco anche di verificare il log di tomcat dove potrebbe esserci una qualche evidenza.

**Comment by LeoLP1** [comment]
Ok grazie, allora proverò ad effettuare nuovamente la parte dell'installazione riguardante il database e nel caso mi dia errori proverò a guardare nuovamente nei log

Grazie
