### ISSUE TITLE
Wish: download dependencies via maven/gradle

### ISSUE THREAD

**Issue by ioggstream** [link-it/govway#7]
## I wish

Build the gateway via maven/gradle without downloading external components

## Instead

I download a static file (eg. can't easily update a vulnerable library)

## Notes

Advantages:

  - integration with https://www.owasp.org/index.php/OWASP_Dependency_Check
  - continuous dependency tracking

**Comment by andreapoli** [comment]
I vantaggi indicati verranno affrontati nell'Issue #22
