### ISSUE TITLE
Comunicazioni con ANPAL - token OAuth2 con expires_in troppo grande

### ISSUE THREAD

**Issue by RegioneMarcheCirillo** [link-it/govway#70]
**Descrizione del Bug**
ANPAL invia un token Client Credential con valore **expires_in = 9223372036854775**; il sistema segnala sempre Token scaduto.

**Come riprodurlo:**
Inviare al sistema un token negoziazione Client Credential del tipo:
`{"access_token":"10aa1676-1f9e-34e2-8515-0cfca111a111","scope":"am_application_scope default","token_type":"Bearer","expires_in":9223372036854775}`

**Risultato atteso:**
Dovrebbe essere utilizzato il Token come "non scaduto"
Da specifiche tale valore dovrebbe indicare un tempo "infinito".

**Ambiente:**

- OS: Ubuntu 18.04
- Browser: tutti
- GovWay: [e.g. 3.2.2]
- AS: Tomcat 9
- Java: openjdk 11.0.8 2020-07-14
- DBMS: MySQL Server version: 5.7.31-0ubuntu0.18.04.1 (Ubuntu)

**Note aggiuntive:**
Io per poter proseguire con l'utilizzo delle API esposte da ANPAL ho ricompilato inserendo questa modifica nel mio codice in locale (preso dal branch  3.3.2.issue69):

_file BasicNegoziazioneTokenParser.java_
_linea 163_

```
			long l = Long.valueOf(tmp);
			if (l > 3153600000) l=3153600000;  // max. scadenza 100 anni 
			if(l>0) {
```
non è la soluzione ottimale ma è la più rapida che ho trovato.
Si potrebbe inserire come correzione (trovando eventualmente qualcosa di migliore)?

**Comment by andreapoli** [comment]
Ciao @RegioneMarcheCirillo, ti ringrazio per la solita dettagliata descrizione.

Ho corretto il problema sul branch [3.3.2.issue69](https://github.com/link-it/govway/tree/3.3.2.issue69) contenente già il fix dell'issue #69. Sono intervenuto esattamente dove da te suggerito, impostando un Long.MAX_VALUE nel caso si verifichi un out of the range del tipo long direttamente durante il parsing del dato presente nel token o dopo l'aggiunta della data in corso di validazione. 

Al solito puoi generarti una nuova versione dell'installer o applicare una patch puntuale seguendo le indicazioni già fornite nell'issue #69.

**Comment by RegioneMarcheCirillo** [comment]
Grazie a te per la rapidità e la precisione: potrò così mettere in produzione il software nel giro di pochi giorni.
