### ISSUE TITLE
WSDL Fruizioni

### ISSUE THREAD

**Issue by LeoLP1** [link-it/govway#71]
Buongiorno stavo provando a recuperare il wsdl della mia fruizione

ho impostato i seguenti parametri

```
# Gestione WSDL sulle fruizioni
org.openspcoop2.pdd.pd.generateWsdl=true
#
# Gestione WSDL sulle erogazioni
org.openspcoop2.pdd.pa.generateWsdl=true
```

e utilizzato il link esposto dalla fruizione con  l'aggiunta di '?wsdl'
ma mi restituisce questo:

`OpenSPCoop2-PD00000-0022`

Mi sapresti dire cosa sbaglio e come faccio a recuperare le wsdl della mia fruizione?
Grazie

**Comment by andreapoli** [comment]
Buongiorno @LeoLP1 .
La funzionalità che hai abilitato permette di ottenere i wsdl con cui sono state registrate le API.
Il codice 'OpenSPCoop2-PD00000-0022' evindenzia invece che l'API associata alla fruizione che stai interrogando è stata creata definendo le risolse manualmente e non tramite il caricamento di un'interfaccia wsdl.
