### ISSUE TITLE
Impossibile connettersi a PostgreSQL DB

### ISSUE THREAD

**Issue by francucchi** [link-it/govway#78]
Salve,
sto cercando di installare GovWay 3.3.3 (postgres version, docker image) su un ambiente OpenShift ospitato su GCP e sto cercando di impostare la connessione ad una istanza di PostgreSQL che ho precedentemente installato e configurato tramite il file SQL di inizializzazione. Purtroppo sembra che la connessione al DB non avvenga mai e il pod pertanto, raggiunto il timeout, continua a crashare. 
Questi i log:

INFO: Preparazione accesso base dati PGSQL ...
INFO: Generazione certificati SSL ...keytool error: java.io.FileNotFoundException: /var/govway/pki/CA_test/ca/certs/ca_test.cert.pem (No such file or directory)
keytool error: java.io.FileNotFoundException: /var/govway/pki/CA_test/ca/certs/ee_test_Client_1.cert.pem (No such file or directory)
keytool error: java.io.FileNotFoundException: /var/govway/pki/CA_test/ca/certs/ee_test_Client_2.cert.pem (No such file or directory)
keytool error: java.lang.Exception: Keystore file does not exist: /var/govway/pki/stores/keystore_server.jks
 Ok.
INFO: Attendo avvio della base dati ...
INFO: Attendo disponibilita' della base dati ..
...
...

Nel file di deployment ho configurato le env per:

GOVWAY_DATABASE_USERNAME
GOVWAY_DATABASE_USERPASSWD
GOVWAY_DATABASE_SERVER
GOVWAY_DATABASE_PORT
GOVWAY_DATABASE_NAME
GOVWAY_INTERFACE

dove la stessa istanza del PostgreSQL (con stesso username/pwd) è utilizzata anche da keycloak deployato nello stesso namespace a confermare la corretta raggiungibilità del servizio stesso.
Ho notato che la sola presenza o meno della GOVWAY_DATABASE_SERVER effettivamente seleziona il driver di riferimento (PGSQL o HSQL) a conferma che le env vengono effettivamente passate al pod. 
Volvevo pertanto verificare con voi se effettivamente l'installazione su OpenShift 4.x sia stata testata e supportata.
Per velocizzare il troubleshooting allego di seguito il file di deployment invocabile come segue:

oc process -f ./govway-openshift-example.yaml -p GOVWAY_DATABASE_SERVER=<indirizzo DB> -p GOVWAY_DATABASE_PORT="5432" -p GOVWAY_DATABASE_NAME=<nome DB> -p GOVWAY_DATABASE_USERNAME=<nome utente> -p GOVWAY_DATABASE_USERPASSWD=<password utente> -p GOVWAY_INTERFACE="rest / web" -p NAMESPACE=<nome namespace> -p APPLICATION_NAME=<nome applicazione> | oc create -f -

Platform:

OpenShift version
4.7.9
Update channel
stable-4.7

Docker image:
GovWay 3.3.3_postgres

PostgreSQL: 
latest docker image

File govway-openshift-example.yaml
================================================================
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: govway
  namespace: openshift-config
  annotations:
    description: An example GovWay server with HTTPS
    iconClass: icon-tomcat
    openshift.io/display-name: GovWay
    tags: java
    version: 9.0.4-SNAPSHOT
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: The web server's https port.
      labels:
        application: '${APPLICATION_NAME}'
      name: '${APPLICATION_NAME}'
    spec:
      ports:
        - port: 8443
          targetPort: 8443
      selector:
        deploymentConfig: '${APPLICATION_NAME}'
  - apiVersion: v1
    id: '${APPLICATION_NAME}'
    kind: Route
    metadata:
      annotations:
        description: Route for application's https service.
      labels:
        application: '${APPLICATION_NAME}'
      name: '${APPLICATION_NAME}'
    spec:
      host: '${HOSTNAME_HTTPS}'
      tls:
        termination: passthrough
      to:
        name: '${APPLICATION_NAME}'
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        application: '${APPLICATION_NAME}'
      name: '${APPLICATION_NAME}'
    spec:
      replicas: 1
      selector:
        deploymentConfig: '${APPLICATION_NAME}'
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            application: '${APPLICATION_NAME}'
            deploymentConfig: '${APPLICATION_NAME}'
          name: '${APPLICATION_NAME}'
        spec:
          containers:
            - name: govway
              image: linkitaly/govway:3.3.3_postgres
              env:
              - name: GOVWAY_DATABASE_USERNAME
                value: '${GOVWAY_DATABASE_USERNAME}'
              - name: GOVWAY_DATABASE_USERPASSWD
                value: '${GOVWAY_DATABASE_USERPASSWD}'
              - name: GOVWAY_DATABASE_SERVER
                value: '${GOVWAY_DATABASE_SERVER}'
              - name: GOVWAY_DATABASE_PORT
                value: '${GOVWAY_DATABASE_PORT}'
              - name: GOVWAY_DATABASE_NAME
                value: '${GOVWAY_DATABASE_NAME}'
              - name: GOVWAY_INTERFACE
                value: '${GOVWAY_INTERFACE}'
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8443
                  name: https
                  protocol: TCP
              securityContext:
                privileged: false
      triggers:
        - type: ConfigChange
parameters:
  - name: APPLICATION_NAME
    displayName: Application Name
    description: The name for the application.
    value: govway
    required: true
  - name: GOVWAY_DATABASE_USERNAME
    displayName: GovWay Database Username
    description: GovWay database username
    generate: expression
    from: '[a-zA-Z0-9]{8}'
    required: true
  - name: GOVWAY_DATABASE_USERPASSWD
    displayName: GovWay Database Password
    description: GovWay database password
    generate: expression
    from: '[a-zA-Z0-9]{8}'
    required: true
  - name: GOVWAY_DATABASE_SERVER
    displayName: GovWay Database Server Address
    description: 'GovWay Database server address'
    value: localhost
    required: true
  - name: GOVWAY_DATABASE_PORT
    displayName: GovWay Database Port
    description: 'GovWay database port'
    value: "5432"
    required: true
  - name: GOVWAY_DATABASE_NAME
    displayName: GovWay Database Name
    description: 'GovWay Database Name'
    value: govway
    required: true
  - name: GOVWAY_INTERFACE
    displayName: GovWay Mode
    description: 'GovWay mode'
    value: "rest / web"
    required: true
  - name: HOSTNAME_HTTPS
    displayName: Custom https Route Hostname
    description: >-
      Custom hostname for https service route. Leave blank for default hostname,
      e.g.: <application-name>-<namespace>.<default-domain-suffix>
  - name: NAMESPACE
    displayName: Namespace used for DNS discovery
    description: >-
      This namespace is a part of DNS query sent to Kubernetes API. This query
      allows the DNS_PING protocol to extract cluster members. This parameter
      might be removed once https://issues.jboss.org/browse/JGRP-2292 is
      implemented.
    required: true

**Comment by marklar79** [comment]
Salve,

confermo che l'immagine docker viene prodotta e testata per ambienti docker-compose e swarm.

Lo script di avvio dell'immagine docker scrive l'output di debug dentro il file:
**/tmp/catalina_wrapper_debug.log**
Recuperandolo dal pod in esecuzione si potrebbe provare a capire il problema.

Va' tenuto conto comunque che Openshift impone dei vincoli che il docker compose non sono presenti; in particolare mi riferisco alla misura di sicurezza di forzare degli UID arbitrari per le utenze di sistema usate sui container.
Questo chiaramente puo portare ad errori negli accessi ai file contenuti nell'immagine.

Nel pezzo di output che hai riportato, vedo che sono presenti anche diversi altri errori, che penso si possano attribuire
proprio a questo fatto.

**Comment by francucchi** [comment]
Salve,
grazie per la info che effettivamente ha risolto il problema visto che era legato proprio ad un discorso di sicurezza.
Volevo chiedere se vi sono delle env da settare per quanto riguarda il livello di logging di govway.

Grazie

**Comment by marklar79** [comment]
Non e' prevista l'impostazione del livello di log attraverso variabili d'ambiente.
In genere e' sufficiente modificare le impostazioni di tracciamento attraverso la govwayConsole: [Configurazione Tracciamento](https://govway.org/documentazione/console/profiloApiGateway/tracciamento.html)

**Comment by francucchi** [comment]
Grazie per il supporto.
