### ISSUE TITLE
Govlet Fatturazione Passiva in modalità pull

### ISSUE THREAD

**Issue by marcomarsala** [link-it/govway#8]
Utilizzando il govlet Fatturazione Passiva, che cosa accade se l’url dell’applicativo interno è down quando il govlet tenta di recapitare una fattura? Viene effettuato un nuovo tentativo? Viene persa?

Sarebbe possibile utilizzare il servizio in modalità pull anziché push (cioè è l’applicativo interno che controlla periodicamente se ci sono fatture ricevute)?

**Comment by andreapoli** [comment]
> Utilizzando il govlet Fatturazione Passiva, che cosa accade se l’url dell’applicativo interno è down quando il govlet tenta di recapitare una fattura? Viene effettuato un nuovo tentativo? Viene persa?

Se l'applicativo non è disponibile viene ritornato un errrore allo SDI il quale schedulerà un nuovo re-invio della fattura.
Maggiori dettagli su questo aspetto sono descritti nel punto e. del paragrafio '4.5 PROCEDURA DI GESTIONE DELLE RICEVUTE E DELLE NOTIFICHE ' all'interno della specifica http://www.fatturapa.gov.it/export/fatturazione/sdi/Specifiche_tecniche_SdI_v1.6.pdf.

**Comment by andreapoli** [comment]
> Sarebbe possibile utilizzare il servizio in modalità pull anziché push (cioè è l’applicativo interno che controlla periodicamente se ci sono fatture ricevute)?

Attivando la console di gestione in modalità 'avanzata' (menù in alto a destra) è possibile utilzzare dei connettori differenti da http.
Per disaccoppiare la ricezione della fattura dalla disponibilità di un applicativo potresti utilizzare il connettore 'file' che consente di serializzare sia la fattura ricevuta che i metadati su filesystem.

**Comment by marcomarsala** [comment]
E se è GovWay a essere down al momento della ricezione di una fattura? Avviene la stessa cosa?

**Comment by marcomarsala** [comment]
> Attivando la console di gestione in modalità 'avanzata' (menù in alto a destra) è possibile utilzzare dei connettori differenti da http.
> Per disaccoppiare la ricezione della fattura dalla disponibilità di un applicativo potresti utilizzare il connettore 'file' che consente di serializzare sia la fattura ricevuta che i metadati su filesystem.

In che modo? L'interfaccia non mi aiuta e nella guida di gestione non ho trovato nulla.
![image](https://user-images.githubusercontent.com/5349718/48757229-57639f00-ec9c-11e8-9789-4b57b3d20efe.png)

**Comment by andreapoli** [comment]
Marco abbiamo aggiornato la guida alla console di gestione per quanto concerne le "parti avanzate".
Nella [guida aggiornata per la console di gestione](https://github.com/link-it/GovWay/blob/master/resources/doc/pdf/GovWay-ManualeUtente.pdf) puoi trovare quello che hai chiesto precedentemente nelle seguenti sezioni:

- 8.3 Modalità Avanzata: ti descrive come attivare la possibilità di configurare le funzionalità avanzate
- 8.7.7 Connettore File: descrive come configurare un connettore di tipo 'file'

**Comment by marcomarsala** [comment]
Grazie. Ho notato che durante la procedura di importazione del govlet non c'è alcun dropdown per selezionare il tipo di connettore, neanche se si parte in modalità avanzata. Per questo ho dovuto modificare in seguito la configurazione da Registro > Erogazioni.

**Comment by andreapoli** [comment]
Si confermo.
L'abilitazione del connettore di tipo 'file' non è selezionabile durante l'utilizzo del govlet ma deve essere eventualmente configurato successivamente come ha fatto tu.

**Comment by andreapoli** [comment]
Nella Fatturazione Passiva, il govlet suddivide le due azioni (RiceviFatture e NotificaDecorrenzaTermini) previste per il servizio RicezioneFatture in due gruppi in modo da rendere possibile una gestione differente del connettore.
Per poter modificare i connettori devi quindi entrare nella gestione della configurazione tramite il link 'Gestione Configurazione' che trovi nel dettaglio dell'erogazione 'RicezioneFatture'.

Mi sono accorto però che se non sei in modalità avanzata di utilizzo della govwayConsole non hai modo di accedere alla configurazione dei connettori. Per questo motivo ho aperto il bug #16.

Per poter accedere alla configurazione dei connettore devi quindi usare la "modalità avanzata" che poi è anche un requisito per poter impostare il connettore di tipo 'file'.
