### ISSUE TITLE
Problema caricamento definizione yaml (openapi: 3.0.0) servizi lavoro ANPAL

### ISSUE THREAD

**Issue by RegioneMarcheCirillo** [link-it/govway#83]
Abbiamo installato GovWay versione 3.3.2.
Nel caricare il file yaml inviatoci da ANPAL per il servizio Ricerca chiamate Intermittenti, otteniamo l'errore:

`[validazione-trasparente] [Interfaccia OpenAPI 3] Documento non valido: org.openspcoop2.utils.rest.ProcessingException: Parse failed: mapping values are not allowed here in 'reader', line 2, column 9: info: ^ at [Source: (StringReader); line: 2, column: 9]`

abbiamo provato ad eseguire un check della definizione usando servizi on-line (es.: https://editor.swagger.io/), ed la definizione viene caricata senza problemi.
Allego il file che non riusciamo a caricare, e la schermata in cui inseriamo la definizione.

Un saluto e grazie
[openapiMarche.yaml.txt](https://github.com/link-it/govway/files/6853596/openapiMarche.yaml.txt)
![APIGW](https://user-images.githubusercontent.com/38277098/126449575-ed61e990-8ce7-427c-8608-168ec75116de.png)

**Comment by andreapoli** [comment]
L'errore avviene solamente se gli elementi principali (openapi, info, servers, paths ...) non sono posizionati sulla prima colonna.

Come workaround puoi modificare l'OpenAPI spostando gli elementi principali. 
Ti allego un esempio ([openapiMarche.yaml_modificato.txt](https://github.com/link-it/govway/files/6854192/openapiMarche.yaml_modificato.txt)) dell'openapi modificato che sono riuscito a caricare senza problemi.
