### ISSUE TITLE
Compatibilità SANP 2.4.x

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govway#86]
Buonasera,
GovWay può sostituire funzionalmente la Porta di Dominio integrando la nuove funzionalità SANP 2.4.x  (Mod 3)?

Grazie.

**Comment by nardil** [comment]
Ciao @giuseppelab , 

la funzione della PdD può essere sostituita da GovWay, mentre la specifica SANP viene implementata da GovPay

**Comment by giuseppelab** [comment]
Ciao Lorenzo,
quindi se sono stretto come tempi di passaggio potrei temporaneamente caricare il nuovo WSDL (non so se è già disponibile) sulla attuale PdD e funziona il nuovo modello 3 ?
Chiaramente la PdD è la Link
Grazie.

**Comment by giuseppelab** [comment]
Si grazie,
al momento ho la 3.4.0, ho visto che le implementazioni sono nella 3.5 per la quale il rilascio sarebbe previsto orientativamente per fine settembre. Intanto farò un giro negli ambienti di collaudo.

Grazie mille.
