### ISSUE TITLE
Supporto per device pkcs11

### ISSUE THREAD

**Issue by tflagella** [link-it/govway#87]
**Necessità:**
Verificare la compatibilità di GovWay con hardware pkcs11, come smart-cart e dispositivi HSM.

**Soluzione:**
Java supporta in maniera trasparente keystore pkcs11 tramite il provider built-in sun.security.pkcs11.SunPKCS11 che può essere configurato per qualunque dispositivo che supporti pkcs11, tramite un parametro con un file di configurazione che punti alla libreria pkcs11 del dispositivo. 

Per mettere a punto uno scenario d'uso si può utilizzare  softhsm, il simulatore pkcs11 di dnssec. Di seguito le istruzione per l'uso su fedora:

1) installare softhm tramite:

   yum install  opensc softhsm

2) predisporre il file /etc/softhsm_java.conf come:

  name = softhsm
  library = /usr/lib64/libsofthsm2.so

3) inizializzare softhsm come segue, fornendo i due pin di gestione e di uso:

   softhsm2-util --init-token --slot 0 --label "Token-1"

4) testare il device virtuale con:

   pkcs11-tool --module /usr/lib64/libsofthsm2.so -l -t

5) A questo punto il dispositivo può essere usato come un normale keystore java:

keytool -list -keystore NONE -storetype PKCS11 -providerClass sun.security.pkcs11.SunPKCS11 -providerArg /etc/softhsm_java.conf

NOTA: Per default l'accesso al device funziona solo da superutente

**Comment by andreapoli** [comment]
Usare opzione -Djava.security.debug=sunpkcs11 per avere i log di debug
