### ISSUE TITLE
Esempio di configurazione govlet Fatturazione Attiva

### ISSUE THREAD

**Issue by marcomarsala** [link-it/GovWay#9]
Buongiorno,

è possibile avere un esempio dei parametri da inserire nella sezione **Autenticazione HTTPS** alla Fase 2/4 dell'importazione del govlet **Fatturazione Attiva**?

La documentazione del govlet presenta alla pagina 5/10 uno screenshot con i campi vuoti.

Ho già completato la richiesta di accreditamente sul sito fatturapa.it ed ho scaricato il kit di test e i certificati client/server per gli ambienti di test e produzione: 

![image](https://user-images.githubusercontent.com/5349718/48408555-e707cb80-e739-11e8-8a1f-b9d79bb88e13.png)

Aprendo i certificati con un doppio click vedo le seguenti informazioni (nello screen il certificato server dell'ambiente di test):

![image](https://user-images.githubusercontent.com/5349718/48408869-ad839000-e73a-11e8-8072-4f951de6049c.png)

nessuna delle quali mi aiuta a compilare i campi richiesti dal govlet.

**Comment by marklar79** [comment]
Per compilare in modo corretto la form, devi assicurarti di avere un keystore che contenga sia la chiave privata utilizzata in fase di accreditamento, sia il certificato CLIENT fornito da fatturapa.it
Il keystore puo' essere fatto in uno qualsiasi dei formati supportati da GovWay anche se i formati piu' utilizzati in genere sono JKS e PKCS12.
Per semplificare puoi inserire il certificato SERVER nello stesso keystore, utilizzandolo quindi sia per l'autenticazioen client che per quella server.
Una volta che avrai creato il keystore, ad esempio un file fatturapa.jks, devi copiarlo sul server dove e' installato GovWay e compilare la form indicando il path in cui hai posizionato il file (ad esempio C:\GovWay\pki\fatturapa.jks).
Sulla form dovrai anche inserire: sia la password utilizzata per la creazione del keystore, sia quella utilizzata per proteggere la chiave privata; questi campi sono entrambi obbligatori quindi assicurati di impostare una password per la chiave privata prima di generare il keystore.
Puoi tranquillamente non modificare i restanti dei campi della form (gli algoritmi).

**Comment by marcomarsala** [comment]
Faccio progressi.
Ho capito che i campi: Path, Tipo, Password e Algoritmo sono relativi al keystore Java dell'Application Server, WildFly nel mio caso.

Nel mio sistema il path del keystore, creato di default con l'installazione di Wildfly è: `/opt/wildfly/standalone/configuration/application.keystore`

Con il comando `keytool -list -keystore /opt/wildfly/standalone/configuration/application.keystore` ottengo in output almeno il tipo: **JKS**.

```
# keytool -list -keystore /opt/wildfly/standalone/configuration/application.keystore
Enter keystore password:

*****************  WARNING WARNING WARNING  *****************
* The integrity of the information stored in your keystore  *
* has NOT been verified!  In order to verify its integrity, *
* you must provide your keystore password.                  *
*****************  WARNING WARNING WARNING  *****************

Keystore type: jks
Keystore provider: SUN

Your keystore contains 1 entry

server, Oct 25, 2018, PrivateKeyEntry,
Certificate fingerprint (SHA1): ???

Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /opt/wildfly/standalone/configuration/application.keystore -destkeystore /opt/wildfly/standalone/configuration/application.keystore -deststoretype pkcs12".
```

Sto ancora cercando di capire quale sia la password di default del keystore di Wildfly. Sul mio sistema è changeit come indicato in rete.

**Comment by marcomarsala** [comment]
> assicurati di impostare una password per la chiave privata prima di generare il keystore.

Ti riferisci alla chiave privata usata per generare le CSR usate per la richiesta di accreditamento? E se avessi usato una chiave privata senza password, devo rifare da capo la richiesta di accreditamento?

**Comment by marklar79** [comment]
No, non è necessario rifare l'accreditamento. La password serve solo a
proteggere la chiave, quindi non cambia anche se imposti la password dopo
aver fatto la CSR.

Il giorno mar 13 nov 2018, 13:15 Marco Marsala <notifications@github.com>
ha scritto:

**Comment by marcomarsala** [comment]
Ho aggiunto la password alla chiave privata utilizzata in fase di accreditamento con OpenSSL:

`openssl rsa -aes256 -in mykey.key -out mykeypassword.key`

Ho creato il keystore con il seguente comando di Java JDK:

`keytool -genkey -validity 365 -keyalg RSA -alias fatturapa -keystore fatturapa.jks`

Vi ho aggiunto i certificati server e client:

```
keytool -importcert -alias client -file SDI-01629370097.cer -keystore fatturapa.jks
keytool -importcert -alias server -file FE.THENETWORKSOLUTION.IT.cer -keystore fatturapa.jks
```

Fin qui è tutto corretto? Comunque non so come aggiungere la chiave privata al keystore.

**Comment by marklar79** [comment]
Per creare un keystore JKS contenente chiave privata e certificati devi necessariamente passare attraverso uno step intermedio, ossia la creazione di un PKCS12. Questo perche', come hai giustamente notato, il comando keytool non consente di importare direttamente chiavi private in un keystore JKS.
I comandi sarebbero quindi questi:

# Creazione PKCS12
 openssl pkcs12 -export -inkey mykeypassword.key -in FE.THENETWORKSOLUTION.IT.cer  -out fatturapa.p12 -name fatturapa_client
# Trasfomazione / Import su JKS
keytool -importkeystore -srckeystore fattura.p12 -srcstoretype pkcs12 -destkeystore fatturapa.jks

Con il keystore fatturapa.jks appena creato se in grado di identificarti come un client accreditato quando chiami il server testservizi.fatturapa.it. Per identificare il server invece, devi importare anche il certificato server di testservizi.fatturapa.it , anzi meglio se importi tutta la catena di certificazione:

# Import CA chain su JKS
keytool -importcert -alias CAEntrate -file CAEntratetest.cer -keystore fatturapa.jks
keytool -importcert -alias testservizi.fatturapa.it -file testservizi.fatturapa.it.cer -keystore fatturapa.jks

A questo utilizzando il keystore fatturapa.jks sei in grado di completare il protocollo TLS e quindi di inviare fatture al server di test.

**Comment by marcomarsala** [comment]
Con il primo comando ottengo:

`unable to load certificates`

**Comment by marcomarsala** [comment]
Nota: Il primo comando ha funzionato solo utilizzando il certificato convertito in formato PEM.

**Comment by marcomarsala** [comment]
> Nota: Il primo comando ha funzionato solo utilizzando il certificato convertito in formato PEM.
> Occhio al typo nel nome del file nel secondo comando

**Comment by marcomarsala** [comment]
Nota: Il primo comando ha funzionato solo utilizzando il certificato convertito in formato PEM.
Occhio al typo nel nome del file nel secondo comando.

**Comment by marklar79** [comment]
Ho editato il commento in modo da tenere conte delle tue giuste osservazioni.
I certificati che hai citato invece sono i certificati client utilizzati dal sistema di interscambio per contattarti.
Quando configurerai il lato server della tua applicazione dovrai ricordarti di inserirli nei rispettivi truststore (test o produzione)

**Comment by marcomarsala** [comment]
Non ho capito cosa intendi per configurare il lato server della mia applicazione. Al momento ho creato fatturapa.jks con i comandi che mi hai indicato sopra, e ora dovrebbe contenere: FE.THENETWORKSOLUTION.IT.cer, la chiave privata, testservizi.fatturapa.it e CAEntratetest.cer. Posso aggiungere a questo jks anche SistemaInterscambioFatturaPATest.cer?

E SDI-pIva.cer dove va messo? Lo aggiungo sempre a questo jks?

**Comment by andreapoli** [comment]
![govway-fatturazioneattiva](https://user-images.githubusercontent.com/16049098/48781008-6453b300-ecdb-11e8-8d51-a4296fc301bc.jpg)
Provo a ricondurre quanto discusso sulla figura sopra riportata. 

# Invio di una fattura allo SDI
L'endpoint https che hai configurato durante l'utilizzo della govlet riguarda la comunicazione in uscita da GovWay verso lo SDI. In questa configurazione il keystore deve contenere:
- la tua chiave privata
- il certificato client che hai ricevuto dallo sdi in seguito alla csr
- testservizi.fatturapa.it
- CAEntratetest.cer

# Ricezione delle notifiche dallo SDI
Lo sdi ti dovrà poi contattare per inviarti le notifiche come descritto nel [manuale](https://github.com/link-it/GovWay/blob/master/resources/doc/pdf/GovWay-ManualeUtente.pdf) nella sezione "5.2.2
Ricezione delle Notifiche dallo SdI". 
GovWay deve essere quindi raggiungibile in https dallo Sdi con una configurazione che contiene i seguenti file:
- la tua chiave privata
- il certificato server che hai ricevuto dallo sdi in seguito alla csr
- SistemaInterscambioFatturaPATest.cer
- CAEntratetest.cer

Sta a te decidere come abiltiare la comunicazione https, utilizzando un frontend  (Apache httpd, IIS, etc) o impostando una porta https direttamente su wildfly.

**Comment by marcomarsala** [comment]
Dovresti avere due certificati: SDI-Client.cer e SDI-Server.cer , immagino che ti riferisca ad uno di questi due quando parli di SDI-pIva.cer.

I file forniti dal sito FatturaPA hanno i seguenti nomi: FE.THENETWORKSOLUTION.IT.cer, SDI-partitaIva.cer

Il colloquio con il sistema di interscambio avviene nei due versi; fin'ora hai configurato solo la parte necessaria a stabilire la comunicazione tra la tua applicazione ed il server SDI (testservizi.fatturapa.it).

Mi è chiaro. Il certificato client serve, in ambito TLS, ad autenticare l’identità del mio server nelle comunicazioni con il SdI.

La configurazione deve essere fatta tramite la govlet di GovWay con l'utilizzo di SDI-Client.cer caricato in questo caso su fatturapa.jks.
Leggendo il tuo commento precedente, mi sono reso conto di aver dato per scontato che il certificato FE.THENETWORKSOLUTION.IT.cer che mi avevi indicato fosse effettivamente SDI-Client.cer,
A questo punto ho pero' il dubbio che possiamo non esserci intesi, quindi sarebbe meglio se tu facessi una verifica sui passi compiuti fin'ora.

Se il certificato caricato su fatturapa.jks non fosse il certificato client purtroppo dovrai rifare il keystore assicurandoti si usare quest'ultimo.

FE.THENETWORKSOLUTION.IT.cer ha CN=fe.thenetworksolution.it, sospetto quindi che sia quello da usare per gli endpoint che espongo io:
Infine per chiudere il discorso sul colloquio con SDI, questo ti contattera' per inviarti le notifiche, e lo fara' all'endpoint che hai fornito in fase di accreditamento.

cioè per questi


L'endpoint deve esporre il certificato server che ti e' stato fornito e deve accettare il certificato client che utilizza lo SDI (SistemaInterscambioFatturaPATest.cer per l'ambiente di test).

Ho capito. L’AdE mi ha fornito il certificato firmato dalla sua CA, per rendere sicura la comunicazione HTTPS con il mio endpoint.

Non capisco perché mi serve avere copia del certificato client del SdI. Se è firmato dalla CA AdE, non basta avere tale CA nell’elenco di quelle fidate?


La configurazione dell'endpoint chiaramente dipende dal web server che utilizzi (Apache httpd, IIS, etc) ma deve utilizzare SDI-Server.cer

Ok, so come procedere.

Spero di aver chiarito un po' la situazione

Si grazie, rifaccio tutto e ti aggiorno.

**Comment by marcomarsala** [comment]
> Dovresti avere due certificati: `SDI-<pIva>Client.cer` e `SDI-<pIva>Server.cer` , immagino che ti riferisca ad uno di questi due quando parli di SDI-pIva.cer.
I file forniti dal sito FatturaPA hanno i seguenti nomi: `FE.THENETWORKSOLUTION.IT.cer e `SDI-`01629370097.cer`
> Il colloquio con il sistema di interscambio avviene nei due versi; fin'ora hai configurato solo la parte necessaria a stabilire la comunicazione tra la tua applicazione ed il server SDI (testservizi.fatturapa.it).
Mi è chiaro. Il certificato client serve, in ambito TLS, ad autenticare l’identità del mio server nelle comunicazioni con il SdI.
> La configurazione deve essere fatta tramite la govlet di GovWay con l'utilizzo di `SDI-<pIva>Client.cer` caricato in questo caso su `fatturapa.jks.`
> 
> Leggendo il tuo commento precedente, mi sono reso conto di aver dato per scontato che il certificato FE.THENETWORKSOLUTION.IT.cer che mi avevi indicato fosse effettivamente `SDI-<pIva>Client.cer,`
> A questo punto ho pero' il dubbio che possiamo non esserci intesi, quindi sarebbe meglio se tu facessi una verifica sui passi compiuti fin'ora.
> Se il certificato caricato su fatturapa.jks non fosse il certificato client purtroppo dovrai rifare il keystore assicurandoti si usare quest'ultimo.
FE.THENETWORKSOLUTION.IT.cer ha CN=fe.thenetworksolution.it, immagino quindi che sia quello da usare per gli endpoint che espongo io.
> Infine per chiudere il discorso sul colloquio con SDI, questo ti contattera' per inviarti le notifiche, e lo fara' all'endpoint che hai fornito in fase di accreditamento.
cioè per questi
> L'endpoint deve esporre il certificato server che ti e' stato fornito e deve accettare il certificato client che utilizza lo SDI (SistemaInterscambioFatturaPATest.cer per l'ambiente di test).
Ho capito. L’AdE mi ha fornito il certificato firmato dalla sua CA, per rendere sicura la comunicazione HTTPS con il mio endpoint.
Non capisco perché mi serve avere copia del certificato client del SdI. Se è firmato dalla CA AdE, non basta avere tale CA nell’elenco di quelle fidate?
> La configurazione dell'endpoint chiaramente dipende dal web server che utilizzi (Apache httpd, IIS, etc) ma deve utilizzare `SDI-<pIva>Server.cer`
Ok, so come procedere.
> Spero di aver chiarito un po' la situazione
Si grazie, rifaccio tutto e ti aggiorno.

Ho notato che nel Kit di Test sono presenti i certificati CA `caentrate.der` e `CAEntratetest.cer` di uguale formato, ma mi sembra che i certificati che ho ricevuto siano firmati dalla prima e che quello di test non viene attualmente usato.

**Comment by marklar79** [comment]
Tutte le segnalazioni che riporti mi sembrano perfettamente valide (tranne quella riguardante il case del nome) e si possono  ricondurre al fatto che la CA di ADE non e' pubblica quindi non e' installata nei truststore dei browser piu' comuni.
Tieni conto pero' che non ci sara' mai accesso via browser dato che si tratta di una comunicazione tra web services, quindi la cosa non e' di fatto un problema.

Per quanto riguarda invece la questione delle due CA se non vedi nessun certificato che abbia come Issuer quella di test, puoi tranquillamente evitare di inserirla

**Comment by marcomarsala** [comment]
Si lo so. L’accesso via browser c’è quando accedo alla console di GovWay, dato che è raggiungibile sotto lo stesso dominio dell’endpoint che espone. Per Chrome so che posso ignorare l’errore, era più che altro una mia curiosità capire come mai solo questo browser non accetta il certificato, nonostante abbia fatto tutte le operazioni sopra indicate.

--
Marco Marsala

Il giorno 21 novembre 2018 @ 11:32:56, Andrea Manca (notifications@github.com<mailto:notifications@github.com>) ha scritto:

Tutte le segnalazioni che riporti mi sembrano perfettamente valide (tranne quella riguardante il case del nome) e si possono ricondurre al fatto che la CA di ADE non e' pubblica quindi non e' installata nei truststore dei browser piu' comuni.
Tieni conto pero' che non ci sara' mai accesso via browser dato che si tratta di una comunicazione tra web services, quindi la cosa non e' di fatto un problema.

Per quanto riguarda invece la questione delle due CA se non vedi nessun certificato che abbia come Issuer quella di test, puoi tranquillamente evitare di inserirla

**Comment by marcomarsala** [comment]
Alla fine ho visto che si può tranquillamente esporre WildFly su due domini diversi tramite reverse proxy sul nginx di frontend, così su quello utilizzato per l’accredito a SDI uso i loro certificati, mentre accedo alla console di gestione dall’altro dominio dove metto un certificato classico di Let’s Encrypt, così il problema è risolto e non ci sono warning in nessun browser quando uso la console.

**Comment by marcomarsala** [comment]
Alla fine ho rifatto da capo chiavi private, CSR e nuova richiesta di accredito. Ho ricevuto i certificati.

Giusto per conferma: ho fatto un unico JKS protetto da password nel quale ho inserito:
- la chiave privata protetta da password
- i due certificati scaricati dal sito FatturaPA > Strumenti > Gestire il canale
- il certificato di testservizi.fatturapa.it che trovo nel kit di test
- il certificato SistemaInterscambioFatturaPATest.cer
- il certificato della CA Entrate di test.

Tutto in un unico file .jks.

Nella configurazione del govlet Fatturazione attiva, alla Fase 2, ho indicato:

- nella sezione Autenticazione server il path di tale .jks e la sua password;
- nella sezione Autenticazione client ho selezionato “Usa valori del TrustStore” e specificato la password della chiave privata.

È corretto? O devo fare due .jks distinti per le due sezioni?

Mi è venuto il dubbio perché mi sono chiesto come faccia il programma a sapere quale certificato prendere visto che nel .jks ora ve ne sono 5.

**Comment by marklar79** [comment]
Si puoi tranquillamente utilizzare un unico jks per contenere tutto facendo la configurazione come hai indicato.
Il software utilizzera' il certificato associato all'unica chiave privata presente nel keystore (saranno presenti di sicuro tre entry di tipo *trustedCertEntry* ed una di tipo *PrivateKeyEntry*)

**Comment by marcomarsala** [comment]
Funziona, grazie
